"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from celery.schedules import crontab
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))
# ---- Redis config (set this before anything that references Redis) ----
REDIS_URL = env('REDIS_TLS_URL', default=None) or env('REDIS_URL', default=None)
REDIS_IS_TLS = bool(REDIS_URL and REDIS_URL.startswith('rediss://'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

DEBUG = env.bool('DEBUG', default=False)

SECRET_KEY = env('DJANGO_SECRET_KEY')
if not SECRET_KEY and DEBUG:
    SECRET_KEY = 'your-dev-safe-django-secret-key'  # Dev fallback
elif not SECRET_KEY:
    raise ImproperlyConfigured("DJANGO_SECRET_KEY is required in production.")

FERNET_KEY = env('FERNET_KEY')
if not FERNET_KEY and DEBUG:
    FERNET_KEY = 'your-dev-safe-fernet-key'  # Dev fallback
elif not FERNET_KEY:
    raise ImproperlyConfigured("FERNET_KEY is required in production.")

# Set to False for local development
CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'default-src': ["'self'"],
        'script-src': [
            "'self'",
            "'unsafe-inline'",
            'https://cdnjs.cloudflare.com',
            'https://cdn.jsdelivr.net',
            'https://algoresearches.s3.us-east-1.amazonaws.com',
        ],
        'style-src': [
            "'self'",
            "'unsafe-inline'",
            'https://fonts.googleapis.com',
            'https://cdn.jsdelivr.net',
            'https://cdnjs.cloudflare.com',
            'https://algoresearches.s3.us-east-1.amazonaws.com',
        ],
        'font-src': [
            "'self'",
            'https://fonts.gstatic.com',
            'https://cdnjs.cloudflare.com',
            'https://algoresearches.s3.us-east-1.amazonaws.com',  # ✅ added
        ],
        'img-src': [
            "'self'",
            'data:',
            'blob:',
            'https://algoresearches.s3.us-east-1.amazonaws.com',
        ],
        'connect-src': [
            "'self'",
            'wss:',
            'https://algoresearches.s3.us-east-1.amazonaws.com',
        ],
        'frame-src': [  # ✅ added
            "'self'",
            'https://www.youtube.com',
            'https://www.youtube-nocookie.com',
        ],
        'frame-ancestors': ["'none'"],
    }
}

if DEBUG:
    CONTENT_SECURITY_POLICY['DIRECTIVES']['script-src'].append("'unsafe-inline'")
    CONTENT_SECURITY_POLICY['DIRECTIVES']['style-src'].append("'unsafe-inline'")

# Final CSP settings after DEBUG adjustments
print(f"🚨 DEBUG is {DEBUG}")


REQUIRED_EMAIL_SETTINGS = [
    'EMAIL_HOST',
    'EMAIL_PORT',
    'EMAIL_HOST_USER',
    'EMAIL_HOST_PASSWORD',
]
if not DEBUG:
    for var in REQUIRED_EMAIL_SETTINGS:
        if not env(var, default=None):
            raise ImproperlyConfigured(f"{var} must be set in production.")
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
if not DEBUG:
    SECURE_SSL_REDIRECT = True  # Enforce HTTPS in production
    
    SECURE_BROWSER_XSS_FILTER = True  # Enable the browser's XSS protection
    X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking by restricting iframe usage
    SECURE_HSTS_SECONDS = 3600  # HTTP Strict Transport Security
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True  # Ensure cookies are only sent via HTTPS
    CSRF_COOKIE_SECURE = True  # Ensure the CSRF cookie is only sent via HTTPS

    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
ALLOWED_HOSTS = [
    'ryanccarmody.com',
    'www.ryanccarmody.com',
    '.herokuapp.com',  # Allow any Heroku subdomain
    '127.0.0.1', 'localhost'
]

INSTALLED_APPS = [
    'captcha',
    "django.contrib.admin",
    "django.contrib.auth",
    'django_celery_beat',  # Optional: Only needed for periodic tasks
    'django_celery_results',  # Optional: To store Celery task results in the d
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    'django.contrib.humanize',
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'channels',
    'dashboard',
    'algoResearchs',
    'myapp',
    'csp',
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.middleware.security.SecurityMiddleware",
    'csp.middleware.CSPMiddleware',  # ✅ Must be early in the list
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    'django.middleware.common.BrokenLinkEmailsMiddleware',
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'dashboard.middleware.TimezoneMiddleware',
    'dashboard.middleware.RoleBasedRedirectMiddleware',
]


CORS_ALLOWED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

INTERNAL_IPS = ['127.0.0.1']



ROOT_URLCONF = "algoResearchs.urls"
CELERY_TASK_TIME_LIMIT = 300  # 5 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 240  # Graceful 4-minute timeout
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

ASGI_APPLICATION = 'algoResearchs.asgi.application'
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [{
                "address": env('REDIS_URL'),
                "ssl_cert_reqs": None  # ✅ Disable SSL cert check
            }],
        },
    },
}


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Ensure 'templates' directory is listed here
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.media',  # Ensure MEDIA_URL is available in templates
                'django.template.context_processors.static',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'dashboard.context_processors.unread_conversations_count',
                'dashboard.context_processors.organization_context',
                'dashboard.context_processors.default_form_context',
            ],
        },
    },
]


APPEND_SLASH = False

WSGI_APPLICATION = "algoResearchs.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# settings.py
import dj_database_url, environ, os
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

if DEBUG:
    DEV_DATABASE_URL = env('DEV_DATABASE_URL', default='')
    if not DEV_DATABASE_URL:
        raise ImproperlyConfigured(
            "DEV_DATABASE_URL is required for local Postgres. "
            "Alternatively, use the SQLite dev config instead."
        )
    DATABASES = {'default': dj_database_url.parse(DEV_DATABASE_URL, conn_max_age=0)}
else:
    DATABASES = {'default': dj_database_url.config(conn_max_age=600, ssl_require=True)}

print("DB ENGINE:", DATABASES['default']['ENGINE'])
print("DB NAME  :", DATABASES['default'].get('NAME', '(via URL)'))

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_USER_MODEL = 'dashboard.User'

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

CSRF_TRUSTED_ORIGINS = [
    "https://ryanccarmody.com",
    "https://www.ryanccarmody.com",
    "https://algoresearch-8340477f6e31.herokuapp.com",
]



AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "us-east-1")
AWS_DEFAULT_ACL = None  # Ensure no ACL issues
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com"
AWS_QUERYSTRING_AUTH = False
AWS_S3_FILE_OVERWRITE = False
STATIC_URL = '/static/'
MEDIA_URL = '/media/'

if not DEBUG:
    # Put static on S3
    STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/static/"
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"

    STORAGES = {
        "default": {"BACKEND": "storages.backends.s3boto3.S3Boto3Storage"},
        "staticfiles": {"BACKEND": "storages.backends.s3boto3.S3Boto3Storage"},
    }

    AWS_S3_OBJECT_PARAMETERS = {
        "CacheControl": "max-age=31536000, public",
    }
else:
    # local dev
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }

LANGUAGE_CODE = "en-us"
TIME_ZONE = 'America/New_York'

USE_TZ = True  # Enables timezone-aware datetime objects

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]



USE_I18N = True
# Celery Settings
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/1'

CELERY_ACCEPT_CONTENT = ['json']  # Content type accepted by Celery
CELERY_TASK_SERIALIZER = 'json'  # Serialize tasks as JSON
CELERY_RESULT_EXPIRES = 3600  # Task results expire after one hour
CELERY_TIMEZONE = TIME_ZONE  # Use the same timezone as Django

# Optional: Celery beat settings for periodic tasks (if needed)
CELERY_BEAT_SCHEDULE = {
    'sample-task': {
        'task': 'dashboard.tasks.sample_task',
        'schedule': crontab(minute=0, hour='*/1'),  # Every hour
    },
}


# Redis Cache for Django (optional, if Redis is used for caching)

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://localhost:6379/2',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
    }
}

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

FILE_UPLOAD_MAX_MEMORY_SIZE = 524288000  # 500 MB, adjust as needed for large videos
DATA_UPLOAD_MAX_MEMORY_SIZE = 524288000  # Match the above limit for consistency


# Authentication settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = '/'


# This should already be there if using DEBUG mode
if DEBUG:
    SECURE_SSL_REDIRECT = False

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

EMAIL_BACKEND = env('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = env('EMAIL_HOST')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_USE_SSL = env.bool('EMAIL_USE_SSL', default=False)  # use True if port 465
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='algoResearch <noreply@ryanccarmody.com>')


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# settings.py

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '{asctime} {levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',  # Adjust verbosity as needed
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'video_processing': {  # Custom logger for video-related tasks
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'websocket': {  # Custom logger for WebSocket messages
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django': {  # General Django logs
            'handlers': ['console'],
            'level': 'WARNING',  # Reduce verbosity for general logs
            'propagate': True,
        },
    },
}
