# Generated by Django 4.2.17 on 2025-04-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_user_position_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="position_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("app_viewer", "Application Viewer"),
                    ("app_editor", "Application Editor"),
                    ("dept_app_editor", "Department Application Editor"),
                    ("proposal_reviewer", "Proposal Reviewer"),
                    ("dept_app_viewer", "Department Application Viewer"),
                ],
                help_text="Defines the specific application-level position",
                max_length=50,
                null=True,
            ),
        ),
    ]
