# Generated by Django 4.2.17 on 2025-04-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_remove_opportunity_agency_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="opportunity", name="agency_name",),
        migrations.AlterField(
            model_name="opportunity",
            name="agency",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
