# Generated by Django 4.2.17 on 2025-04-16 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_remove_opportunity_agency_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="opportunity", name="agency",),
    ]
