# Generated by Django 4.2.17 on 2025-04-16 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_remove_opportunity_agency"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="agency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.agency",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="position_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("app_viewer", "Application Viewer"),
                    ("app_editor", "Application Editor"),
                    ("dept_app_editor", "Department Application Editor"),
                    ("proposal_reviewer", "Proposal Reviewer"),
                    ("dept_app_viewer", "Department Application Viewer"),
                    ("agency_user", "Agency Representative"),
                ],
                help_text="Defines the specific application-level position",
                max_length=50,
                null=True,
            ),
        ),
    ]
