# Generated by Django 4.2.17 on 2025-04-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_user_agency_alter_user_position_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="submittedpackage",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("routed", "Routed to Agency"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
