# Generated by Django 4.2.17 on 2025-04-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_submittedpackage_approval_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("Development", "Development"),
                    ("Under Review", "Under Review"),
                    ("Approved", "Approved"),
                    ("Submitted to Sponsor", "Submitted to Sponsor"),
                    ("Funded", "Funded"),
                    ("Closed", "Closed"),
                ],
                default="Development",
                max_length=50,
            ),
        ),
    ]
