# Generated by Django 4.2.17 on 2025-04-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0016_alter_user_position_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="award_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
