# Generated by Django 4.2.17 on 2025-04-22 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0018_fund_project_fund"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectFinancials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "budget_direct_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "budget_fa",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=12, verbose_name="F&A"
                    ),
                ),
                (
                    "budget_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "expenses_direct_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "expenses_fa",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=12, verbose_name="F&A"
                    ),
                ),
                (
                    "expenses_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "balance_direct_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "balance_fa",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=12, verbose_name="F&A"
                    ),
                ),
                (
                    "balance_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "encumbrance_direct_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "encumbrance_fa",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=12, verbose_name="F&A"
                    ),
                ),
                (
                    "encumbrance_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "projected_direct_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "projected_fa",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=12, verbose_name="F&A"
                    ),
                ),
                (
                    "projected_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "projected_balance_direct_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "projected_balance_fa",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=12, verbose_name="F&A"
                    ),
                ),
                (
                    "projected_balance_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financials",
                        to="dashboard.project",
                    ),
                ),
            ],
        ),
    ]
