# Generated by Django 4.2.17 on 2025-04-22 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0021_costtype_is_idc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="principal_investigator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pi_for_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
