# Generated by Django 4.2.17 on 2025-04-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0024_alter_project_principal_investigator"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="budget_periods",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
