# Generated by Django 4.2.17 on 2025-04-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0026_projectbudgetperiod"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="unique_id",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="System-generated 10-digit unique identifier for user tracking",
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
    ]
