# Generated by Django 4.2.17 on 2025-04-23 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0027_user_unique_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlossaryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(max_length=255)),
                ("definition", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glossary_items",
                        to="dashboard.organization",
                    ),
                ),
            ],
        ),
    ]
