# Generated by Django 4.2.17 on 2025-04-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0028_glossaryitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="benefits_package",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FAC", "FAC"),
                    ("FT", "FT"),
                    ("Gen", "Gen"),
                    ("GenPT", "GenPT"),
                    ("None", "None"),
                    ("PT", "PT"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="pay_period",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Bimonthly", "Bimonthly"),
                    ("Biweekly", "Biweekly"),
                    ("Weekly", "Weekly"),
                    ("Monthly", "Monthly"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="pay_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Salary", "Salary"),
                    ("Hourly", "Hourly"),
                    ("1 time payment", "1 time payment"),
                    ("2 Month Payment", "2 Month Payment"),
                    ("3 Month Payment", "3 Month Payment"),
                    ("4 Month Payment", "4 Month Payment"),
                    ("5 Month Payment", "5 Month Payment"),
                    ("6 Month Payment", "6 Month Payment"),
                    ("7 Month Payment", "7 Month Payment"),
                    ("8 Month Payment", "8 Month Payment"),
                    ("9 Month Payment", "9 Month Payment"),
                    ("10 Month Payment", "10 Month Payment"),
                    ("11 Month Payment", "11 Month Payment"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
