# Generated by Django 4.2.17 on 2025-04-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0029_user_benefits_package_user_pay_period_user_pay_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="glossaryitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("corporation_code", "Corporation Code"),
                    ("object_set", "Object Set"),
                    ("object_code", "Object Code"),
                    ("cost_center", "Cost Center"),
                ],
                default="corporation_code",
                max_length=50,
            ),
        ),
    ]
