# Generated by Django 4.2.17 on 2025-04-24 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0030_glossaryitem_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_name", models.CharField(max_length=255)),
                ("employee_id", models.CharField(max_length=20)),
                ("position", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "corporation_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("object_set", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "object_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "cost_center",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "benefits_package",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("pay_type", models.CharField(blank=True, max_length=30, null=True)),
                ("pay_period", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "hours_worked",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_entries",
                        to="dashboard.fund",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_entries",
                        to="dashboard.organization",
                    ),
                ),
            ],
        ),
    ]
