# Generated by Django 4.2.17 on 2025-04-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0031_employeeentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="costtype",
            name="category",
            field=models.CharField(
                choices=[
                    ("personnel", "Personnel"),
                    ("non_personnel", "Non-Personnel"),
                ],
                default="non_personnel",
                max_length=20,
            ),
        ),
    ]
