# Generated by Django 4.2.17 on 2025-04-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0032_costtype_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectbudgetperiod",
            name="budget_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
