# Generated by Django 4.2.17 on 2025-04-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0035_budgetallocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="costentry",
            name="expense",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
