# Generated by Django 4.2.17 on 2025-04-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0037_userfundassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="costtype",
            name="cost_center_type",
            field=models.CharField(
                choices=[("direct", "Direct"), ("indirect", "Indirect")],
                default="direct",
                max_length=10,
            ),
        ),
    ]
