# Generated by Django 4.2.17 on 2025-04-27 21:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0038_costtype_cost_center_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="costentry",
            name="account2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="costentry",
            name="accounting_period",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="costentry",
            name="check_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="costentry",
            name="cost_center",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="costentry",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="costentry",
            name="flex1_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="costentry",
            name="flex2_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="costentry",
            name="fund",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cost_entries",
                to="dashboard.fund",
            ),
        ),
        migrations.AddField(
            model_name="costentry",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="costentry",
            name="object_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="costentry",
            name="object_set",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="costentry",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cost_entries",
                to="dashboard.organization",
            ),
        ),
        migrations.AddField(
            model_name="costentry",
            name="program",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="costentry",
            name="transaction_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
