# Generated by Django 4.2.17 on 2025-04-27 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0039_costentry_account2_costentry_accounting_period_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="costentry", name="flex1_id",),
        migrations.RemoveField(model_name="costentry", name="flex2_id",),
        migrations.AddField(
            model_name="costentry",
            name="flex1",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="costentry",
            name="flex2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="costentry",
            name="account2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="costentry",
            name="accounting_period",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="costentry",
            name="check_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="costentry",
            name="fund",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.fund",
            ),
        ),
        migrations.AlterField(
            model_name="costentry",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="costentry",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.organization",
            ),
        ),
    ]
