# Generated by Django 4.2.17 on 2025-04-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0040_remove_costentry_flex1_id_remove_costentry_flex2_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="costentry",
            name="code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="costentry",
            name="ref_num1",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="costentry",
            name="ref_num2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="costentry",
            name="vendor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
