# Generated by Django 4.2.17 on 2025-04-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0041_costentry_code_costentry_ref_num1_costentry_ref_num2_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="costentry",
            name="is_reference",
            field=models.BooleanField(default=False),
        ),
    ]
