# Generated by Django 4.2.17 on 2025-04-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0044_delete_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dark_mode",
            field=models.BooleanField(
                default=False, help_text="Enable dark mode for this user"
            ),
        ),
    ]
