# Generated by Django 4.2.17 on 2025-05-02 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0049_calendarevent_linked_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_calendar_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
