# Generated by Django 4.2.17 on 2025-05-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0054_user_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="idc_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="IDC rate as a percentage (e.g. 30.00 for 30%)",
                max_digits=5,
            ),
        ),
    ]
