# Generated by Django 4.2.17 on 2025-05-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0057_remove_iacucsubmission_protocol_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="iacucsubmission", name="end_date",),
        migrations.RemoveField(model_name="iacucsubmission", name="procedures",),
        migrations.RemoveField(model_name="iacucsubmission", name="species",),
        migrations.RemoveField(model_name="iacucsubmission", name="start_date",),
    ]
