# Generated by Django 4.2.17 on 2025-05-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0059_remove_iacucsubmission_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="iacucsubmission",
            name="external_collaboration",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="iacucsubmission",
            name="federal_funding",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="iacucsubmission",
            name="field_studies",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="iacucsubmission",
            name="housing_outside_facility_12hr",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="iacucsubmission",
            name="internal_federal_funding",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="iacucsubmission",
            name="off_campus_live_animal_work",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="iacucsubmission",
            name="private_commercial_funding",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="iacucsubmission",
            name="public_area_transport",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="iacucsubmission",
            name="uses_outside_tissues",
            field=models.BooleanField(default=False),
        ),
    ]
