# Generated by Django 4.2.17 on 2025-05-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0061_iacucprotocolspecies"),
    ]

    operations = [
        migrations.AddField(
            model_name="iacucsubmission",
            name="benefits",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="iacucsubmission",
            name="experimental_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="iacucsubmission",
            name="lay_abstract",
            field=models.TextField(blank=True, null=True),
        ),
    ]
