# Generated by Django 4.2.17 on 2025-05-05 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0062_iacucsubmission_benefits_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IACUCFundingSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=255)),
                ("grant_title", models.CharField(max_length=255)),
                ("funded", models.BooleanField(default=False)),
                ("pi_on_grant", models.BooleanField(default=False)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_sources",
                        to="dashboard.iacucsubmission",
                    ),
                ),
            ],
        ),
    ]
