# Generated by Django 4.2.17 on 2025-05-05 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0063_iacucfundingsource"),
    ]

    operations = [
        migrations.CreateModel(
            name="IACUCInternalFundingSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization", models.CharField(max_length=255)),
                ("department", models.CharField(max_length=255)),
                ("fund_title", models.CharField(max_length=255)),
                ("sponsored_projects_number", models.CharField(max_length=100)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internal_funding_sources",
                        to="dashboard.iacucsubmission",
                    ),
                ),
            ],
        ),
    ]
