# Generated by Django 4.2.17 on 2025-05-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0065_iacucprivatefundingsource"),
    ]

    operations = [
        migrations.AddField(
            model_name="iacucsubmission",
            name="source_assurance_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="iacucsubmission",
            name="source_protocol_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
