# Generated by Django 4.2.17 on 2025-05-05 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0066_iacucsubmission_source_assurance_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalCollaboration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_name", models.CharField(max_length=255)),
                ("assurance_number", models.CharField(max_length=255)),
                ("protocol_number", models.CharField(max_length=255)),
                ("species_list", models.TextField()),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_collaborations",
                        to="dashboard.iacucsubmission",
                    ),
                ),
            ],
        ),
    ]
