# Generated by Django 4.2.17 on 2025-05-05 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0070_publictransportuse"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldStudyDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.TextField()),
                ("animals_captured", models.BooleanField(default=False)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_study_details",
                        to="dashboard.iacucsubmission",
                    ),
                ),
            ],
        ),
    ]
