# Generated by Django 4.2.17 on 2025-05-05 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0071_fieldstudydetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="WildlifeCapture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipment_used", models.TextField()),
                ("trapping_duration", models.TextField()),
                ("monitoring_protocol", models.TextField()),
                ("capture_myopathy_treatment", models.TextField()),
                ("opportunistic_species", models.TextField()),
                ("release_procedure", models.TextField()),
                (
                    "transport_type",
                    models.CharField(
                        choices=[
                            ("none", "Animals Will Not Be Transported"),
                            ("live", "Live Animals Will Be Transported"),
                            ("dead", "Dead Animals Will Be Transported"),
                            ("both", "Both Live and Dead Animals Will Be Transported"),
                        ],
                        max_length=50,
                    ),
                ),
                ("transport_description", models.TextField()),
                ("animals_tagged", models.BooleanField(default=False)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wildlife_capture",
                        to="dashboard.iacucsubmission",
                    ),
                ),
            ],
        ),
    ]
