# Generated by Django 4.2.17 on 2025-05-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0072_wildlifecapture"),
    ]

    operations = [
        migrations.AddField(
            model_name="wildlifecapture",
            name="health_observations",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="wildlifecapture",
            name="measurement_frequency",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="wildlifecapture",
            name="normal_ranges",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="wildlifecapture",
            name="out_of_range_protocol",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="wildlifecapture",
            name="physiological_parameters",
            field=models.TextField(blank=True),
        ),
    ]
