# Generated by Django 4.2.17 on 2025-05-05 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0073_wildlifecapture_health_observations_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldSafetyPrecautions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("decontamination_procedures", models.TextField()),
                ("ppe_description", models.TextField()),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_safety",
                        to="dashboard.iacucsubmission",
                    ),
                ),
            ],
        ),
    ]
