# Generated by Django 4.2.17 on 2025-05-05 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0075_fieldstudypermit"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeciesBreeding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transgenic_flag", models.BooleanField(default=False)),
                ("maintain_colony", models.BooleanField(default=False)),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breeding_entry",
                        to="dashboard.iacucprotocolspecies",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="species_breeding_forms",
                        to="dashboard.iacucsubmission",
                    ),
                ),
            ],
            options={"unique_together": {("submission", "species")},},
        ),
    ]
