# Generated by Django 4.2.17 on 2025-05-06 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0076_speciesbreeding"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeciesProcedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("procedure_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedure_entry",
                        to="dashboard.iacucprotocolspecies",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="species_procedures",
                        to="dashboard.iacucsubmission",
                    ),
                ),
            ],
            options={"unique_together": {("submission", "species")},},
        ),
    ]
