# Generated by Django 4.2.17 on 2025-05-06 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0078_speciesrestraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeciesSurgery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "surgery_type",
                    models.CharField(
                        choices=[
                            ("catheterization", "Catheterization"),
                            ("implant", "Implant"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "other_surgery_description",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "recovery_type",
                    models.CharField(
                        choices=[
                            ("recovery", "Recovery"),
                            ("no_recovery", "No Recovery"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surgery_entry",
                        to="dashboard.iacucprotocolspecies",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="species_surgery_forms",
                        to="dashboard.iacucsubmission",
                    ),
                ),
            ],
            options={"unique_together": {("submission", "species")},},
        ),
    ]
