# Generated by Django 4.2.17 on 2025-05-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0080_speciessurgery_analgesics_withheld_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="speciessurgery",
            name="surgery_location_building",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="speciessurgery",
            name="surgery_location_room",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="speciessurgery",
            name="surgery_location_type",
            field=models.CharField(
                blank=True,
                choices=[("housing", "Housing"), ("use", "Use")],
                max_length=20,
            ),
        ),
    ]
