# Generated by Django 4.2.17 on 2025-05-06 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0082_speciesmss"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeciesVetDrug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generic_name", models.CharField(max_length=255)),
                ("drug_type", models.CharField(max_length=255)),
                ("dose", models.CharField(max_length=100)),
                ("frequency", models.CharField(max_length=100)),
                ("route_admin", models.JSONField(default=list)),
                ("procedure_use", models.TextField()),
                ("is_pharma_grade", models.BooleanField()),
                ("non_pharma_justification", models.TextField(blank=True)),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.iacucprotocolspecies",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.iacucsubmission",
                    ),
                ),
            ],
        ),
    ]
