# Generated by Django 4.2.17 on 2025-05-06 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0084_hazardousagent"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeciesEuthanasia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CO2", "Carbon Dioxide Inhalation"),
                            ("CD", "Cervical Dislocation"),
                            ("DEC", "Decapitation"),
                        ],
                        max_length=10,
                    ),
                ),
                ("justification", models.TextField(blank=True)),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.iacucprotocolspecies",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.iacucsubmission",
                    ),
                ),
            ],
        ),
    ]
