# Generated by Django 4.2.17 on 2025-05-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0086_specieseuthanasia_num_b_specieseuthanasia_num_c_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="specieseuthanasia",
            name="euthanasia_criteria",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="specieseuthanasia",
            name="pain_distress",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="specieseuthanasia",
            name="pain_nature",
            field=models.TextField(blank=True),
        ),
    ]
