# Generated by Django 4.2.17 on 2025-05-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0089_specieseuthanasia_reduce_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="specieseuthanasia",
            name="adverse_reactions_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="specieseuthanasia",
            name="adverse_reactions_expected",
            field=models.BooleanField(default=False),
        ),
    ]
