# Generated by Django 4.2.17 on 2025-05-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0091_databasesearch"),
    ]

    operations = [
        migrations.AddField(
            model_name="iacucsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_review", "In Review"),
                    ("approved", "Approved"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
