# Generated by Django 4.2.17 on 2025-05-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0092_iacucsubmission_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="iacucsubmission",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="iacucsubmission",
            name="procedures",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="iacucsubmission",
            name="species",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="iacucsubmission",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="iacucsubmission",
            name="upload",
            field=models.FileField(blank=True, null=True, upload_to="iacuc_uploads/"),
        ),
    ]
