# Generated by Django 4.2.17 on 2025-05-07 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0095_irbsubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="irbsubmission",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="irbsubmission",
            name="external_irb",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="irbsubmission",
            name="pi_financial_interest",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="irbsubmission",
            name="principal_investigator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="irb_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="irbsubmission",
            name="short_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="irbsubmission",
            name="site_type",
            field=models.CharField(
                blank=True,
                choices=[("single", "Single Site"), ("multi", "Multi Site")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="irbsubmission",
            name="study_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("biomedical", "Biomedical"),
                    ("behavioral", "Behavioral"),
                    ("chart_review", "Chart Review"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
