# Generated by Django 4.2.17 on 2025-05-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0096_irbsubmission_description_irbsubmission_external_irb_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="irbsubmission", name="study_type",),
        migrations.AlterField(
            model_name="irbsubmission",
            name="external_irb",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], default=False
            ),
        ),
        migrations.AlterField(
            model_name="irbsubmission",
            name="pi_financial_interest",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], default=False
            ),
        ),
    ]
