# Generated by Django 4.2.17 on 2025-05-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0103_alter_irbsubmission_funding_additional_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="irbsubmission",
            name="exclusion_criteria",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="irbsubmission",
            name="inclusion_criteria",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="irbsubmission",
            name="study_purpose",
            field=models.TextField(blank=True),
        ),
    ]
