# Generated by Django 4.2.17 on 2025-05-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0104_irbsubmission_exclusion_criteria_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="irbsubmission", name="exclusion_criteria",),
        migrations.RemoveField(model_name="irbsubmission", name="inclusion_criteria",),
        migrations.RemoveField(model_name="irbsubmission", name="study_purpose",),
        migrations.AddField(
            model_name="irbsubmission",
            name="uses_device",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="irbsubmission",
            name="uses_drug_or_biologic",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
