# Generated by Django 4.2.17 on 2025-05-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0108_irbstudydevice"),
    ]

    operations = [
        migrations.AddField(
            model_name="irbsubmission",
            name="device_exemption_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("IDE", "IDE"),
                    (
                        "Abbreviated IDE",
                        "Claim of Abbreviated IDE (Nonsignificant Risk Device)",
                    ),
                    ("Exempt", "Exempt from IDE Requirements"),
                    ("Not Applicable", "Not Applicable"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="irbsubmission",
            name="evaluates_device_safety_effectiveness",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
