# Generated by Django 4.2.17 on 2025-05-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0111_alter_irbsubmission_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="irbstudydevice",
            name="exemption_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("IDE", "IDE"),
                    (
                        "Abbreviated IDE",
                        "Claim of Abbreviated IDE (Nonsignificant Risk Device)",
                    ),
                    ("Exempt", "Exempt from IDE Requirements"),
                    ("Not Applicable", "Not Applicable"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
