# Generated by Django 4.2.17 on 2025-05-09 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0112_alter_irbstudydevice_exemption_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="irbsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Pre Submission", "Pre Submission"),
                    ("Pre Review", "Pre Review"),
                    ("Revision", "Revision"),
                    ("IRB Review", "IRB Review"),
                    ("IRB Review Revision", "IRB Review Revision"),
                    ("Post IRB Review", "Post IRB Review"),
                    ("Post IRB Review Revision", "Post IRB Review Revision"),
                    ("Approved", "Approved"),
                ],
                default="Draft",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="IACUCCommittee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="iacuc_committee",
                        to="dashboard.organization",
                    ),
                ),
            ],
        ),
    ]
