# Generated by Django 4.2.17 on 2025-05-09 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0115_alter_iacucmember_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="iacucsubmission",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True,
                related_name="iacuc_shared_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="iacucsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pre_submission", "Pre-Submission"),
                    ("admin_review", "Administrative Review"),
                    ("pre_review", "Pre-Review"),
                    ("iacuc_review", "IACUC Review"),
                    ("post_review", "Post Review"),
                    ("approved", "Approved"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
