# Generated by Django 4.2.17 on 2025-05-09 23:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0122_iacucsubmission_pre_review_member_approved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="iacucmember",
            name="iacuc_approvals",
            field=models.ManyToManyField(
                blank=True,
                related_name="iacuc_approved_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
