# Generated by Django 4.2.17 on 2025-05-10 00:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0123_iacucmember_iacuc_approvals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iacucmember",
            name="iacuc_approvals",
            field=models.ManyToManyField(
                blank=True,
                related_name="approved_iacuc_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
