# Generated by Django 4.2.17 on 2025-05-10 00:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0124_alter_iacucmember_iacuc_approvals"),
    ]

    operations = [
        migrations.AddField(
            model_name="iacucsubmission",
            name="iacuc_approvals",
            field=models.ManyToManyField(
                blank=True,
                related_name="iacuc_submissions_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
