# Generated by Django 4.2.17 on 2025-05-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0128_iacucpersonnel"),
    ]

    operations = [
        migrations.AddField(
            model_name="iacucpersonnel",
            name="activities_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="iacucpersonnel",
            name="training_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="iacucpersonnel",
            name="training_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="iacucpersonnel",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
