# Generated by Django 4.2.17 on 2025-05-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0129_iacucpersonnel_activities_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="iacucpersonnel",
            name="degrees",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="iacucpersonnel",
            name="experience_and_qualifications",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="iacucpersonnel",
            name="orientation_training_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="iacucpersonnel",
            name="submitted_achs_questionnaire",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="iacucpersonnel",
            name="years_of_experience",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
