# Generated by Django 4.2.17 on 2025-05-11 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0133_iacucprotocolspecies_other_justification_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeciesUseLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("room", models.CharField(max_length=255)),
                (
                    "location_type",
                    models.CharField(
                        choices=[("housing", "Housing"), ("use", "Use")], max_length=10
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.iacucprotocolspecies",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.iacucsubmission",
                    ),
                ),
            ],
            options={"unique_together": {("submission", "species")},},
        ),
    ]
