# Generated by Django 4.2.17 on 2025-05-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0134_speciesuselocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speciesuselocation",
            name="location_type",
            field=models.CharField(
                choices=[("housing", "Housing"), ("use", "Use")], max_length=20
            ),
        ),
    ]
