# Generated by Django 4.2.17 on 2025-05-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0137_speciesstrain"),
    ]

    operations = [
        migrations.AddField(
            model_name="iacucnote",
            name="section_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
