# Generated by Django 4.2.17 on 2025-05-12 21:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0140_iacucsubmission_dmr_approvals_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="iacucsubmission",
            name="dmr_reviewer_approvals",
            field=models.ManyToManyField(
                blank=True,
                related_name="dmr_reviewer_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="iacucsubmission",
            name="dmr_reviewers",
            field=models.ManyToManyField(
                blank=True, related_name="dmr_reviewers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
