# Generated by Django 4.2.17 on 2025-05-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0144_iacucsubmission_annual_review_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="iacucsubmission",
            name="progress_report",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="iacucsubmission",
            name="renewal_status",
            field=models.CharField(
                blank=True,
                choices=[("continue", "Continue as Is"), ("withdraw", "Withdraw")],
                max_length=20,
                null=True,
            ),
        ),
    ]
