# Generated by Django 4.2.17 on 2025-05-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0147_iacucpersonnel_adverse_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="iacucpersonnel",
            name="alternative_to_animal_use",
            field=models.TextField(blank=True, null=True),
        ),
    ]
