# Generated by Django 4.2.17 on 2025-05-13 18:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0148_iacucpersonnel_alternative_to_animal_use"),
    ]

    operations = [
        migrations.RemoveField(model_name="iacucpersonnel", name="adverse_events",),
        migrations.RemoveField(
            model_name="iacucpersonnel", name="alternative_to_animal_use",
        ),
        migrations.RemoveField(model_name="iacucpersonnel", name="renewal_personnel",),
        migrations.AddField(
            model_name="iacucsubmission",
            name="adverse_events",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="iacucsubmission",
            name="alternative_to_animal_use",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="iacucsubmission",
            name="renewal_personnel",
            field=models.ManyToManyField(
                blank=True,
                related_name="renewal_personnel",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
