# Generated by Django 4.2.17 on 2025-05-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0149_remove_iacucpersonnel_adverse_events_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="iacucsubmission",
            name="alt_to_procedures",
            field=models.TextField(blank=True, null=True),
        ),
    ]
