# Generated by Django 4.2.17 on 2025-05-13 21:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0152_iacucsubmission_future_use_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="irbsubmission",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True,
                related_name="irb_shared_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
