# Generated by Django 4.2.17 on 2025-05-13 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0154_irbcertification"),
    ]

    operations = [
        migrations.CreateModel(
            name="IRBCommittee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="irb_committee",
                        to="dashboard.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IRBMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("office_member", "IRB Office Member"),
                            ("analyst", "IRB Analyst"),
                            ("chair", "IRB Chair"),
                            ("non_scientist", "IRB Non-Scientist"),
                            ("scientist", "IRB Scientist"),
                            ("non_affiliated", "IRB Non-Affiliated"),
                            ("community_member", "IRB Community Member"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                (
                    "committee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="dashboard.irbcommittee",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="irb_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("committee", "user")},},
        ),
    ]
