# Generated by Django 4.2.17 on 2025-05-15 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0161_irbnote"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disclosure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "disclosure_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual Disclosure"),
                            ("research", "Research-Based Disclosure"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disclosures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
