# Generated by Django 4.2.17 on 2025-05-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0164_disclosure_is_phs_supported"),
    ]

    operations = [
        migrations.AddField(
            model_name="disclosure",
            name="has_public_entity_interest",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
