# Generated by Django 4.2.17 on 2025-05-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0167_disclosure_has_intellectual_property"),
    ]

    operations = [
        migrations.AddField(
            model_name="disclosure",
            name="ip_acquisition_by_entity",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
