# Generated by Django 4.2.17 on 2025-05-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0168_disclosure_ip_acquisition_by_entity"),
    ]

    operations = [
        migrations.AddField(
            model_name="disclosure",
            name="has_sponsored_travel",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="disclosure",
            name="mentorship_conflict_interest",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
