# Generated by Django 4.2.17 on 2025-05-21 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0171_userdictionaryentry"),
    ]

    operations = [
        migrations.AlterModelOptions(name="userdictionaryentry", options={},),
        migrations.AlterUniqueTogether(
            name="userdictionaryentry", unique_together=set(),
        ),
        migrations.AlterField(
            model_name="userdictionaryentry",
            name="category",
            field=models.CharField(
                choices=[
                    ("funding", "Funding"),
                    ("organization", "Organization"),
                    ("institution", "Institution"),
                    ("location", "Location"),
                    ("procedure", "Procedure"),
                    ("drug", "Drug"),
                    ("agent", "Agent"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="FundingGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grant_number", models.CharField(max_length=255)),
                (
                    "dictionary_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grants",
                        to="dashboard.userdictionaryentry",
                    ),
                ),
            ],
        ),
    ]
