# Generated by Django 4.2.17 on 2025-05-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0173_organizationdepartment"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdictionaryentry",
            name="drug_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
