# Generated by Django 4.2.17 on 2025-05-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0174_userdictionaryentry_drug_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdictionaryentry",
            name="agent_category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userdictionaryentry",
            name="agent_class",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
