# Generated by Django 4.2.17 on 2025-05-22 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0177_alter_iacucinternalfundingsource_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iacucinternalfundingsource",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="funding_sources",
                to="dashboard.organizationdepartment",
            ),
        ),
    ]
