# Generated by Django 4.2.17 on 2025-05-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0182_iacucsubmission_original_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="iacucsubmission",
            name="significance_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("significant", "Significant"),
                    ("non_significant", "Non-Significant"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
