# Generated by Django 4.2.17 on 2025-05-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0183_iacucsubmission_significance_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iacucsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pre_submission", "Pre-Submission"),
                    ("admin_review", "Administrative Review"),
                    (
                        "awaiting_significance_confirmation",
                        "Awaiting Significance Confirmation",
                    ),
                    ("pre_review", "Pre-Review"),
                    ("chair_review", "Chair Designation"),
                    ("dmr_review", "Designated Member Review"),
                    ("iacuc_review", "IACUC Review"),
                    ("post_review", "Post Review"),
                    ("approved", "Approved"),
                ],
                default="draft",
                max_length=35,
            ),
        ),
    ]
