# Generated by Django 4.2.17 on 2025-05-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0185_iacucsubmission_is_superseded"),
    ]

    operations = [
        migrations.AddField(
            model_name="iacucsubmission",
            name="animal_disposition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("leave_with_pi", "Leave with PI"),
                    ("transfer", "Transfer to another protocol"),
                    ("none", "No animals left"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
