# Generated by Django 4.2.17 on 2025-07-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0196_alter_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='irbsubmission',
            name='analyst_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='irbsubmission',
            name='certification_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='irbsubmission',
            name='final_approval_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='irbsubmission',
            name='irb_board_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='irbsubmission',
            name='irb_office_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
