# Generated by Django 4.2.17 on 2025-07-31 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0198_conversation_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='irbsubmission',
            name='analyst_reviewed',
        ),
        migrations.RemoveField(
            model_name='irbsubmission',
            name='certification_complete',
        ),
        migrations.RemoveField(
            model_name='irbsubmission',
            name='final_approval_complete',
        ),
        migrations.RemoveField(
            model_name='irbsubmission',
            name='irb_board_reviewed',
        ),
        migrations.RemoveField(
            model_name='irbsubmission',
            name='irb_office_reviewed',
        ),
    ]
