# Generated by Django 4.2.15 on 2024-08-17 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
        migrations.AlterField(
            model_name="friend", name="status", field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="friend",
            name="user2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friend_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
