# Generated by Django 5.1.1 on 2024-11-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="animal", unique_together=set(),),
        migrations.AlterField(
            model_name="animal",
            name="rfid_tag",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="rfidassignment",
            name="rfid",
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name="animal",
            constraint=models.UniqueConstraint(
                fields=("organization", "rfid_tag"), name="unique_rfid_per_organization"
            ),
        ),
        migrations.AddConstraint(
            model_name="animal",
            constraint=models.UniqueConstraint(
                fields=("organization", "animal_index"),
                name="unique_animal_index_per_organization",
            ),
        ),
    ]
