# Generated by Django 4.2.20 on 2025-04-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submittedpackage",
            name="RR_Other_Info_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
