# Generated by Django 5.1.1 on 2024-11-11 21:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="assigned_users",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_animals", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="cage",
            name="assigned_users",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_cages", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="type",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("group", "Group"),
                    ("notification", "Notification"),
                ],
                default="private",
                max_length=20,
            ),
        ),
    ]
