# Generated by Django 4.2.17 on 2025-04-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectattachment",
            name="file_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
