# Generated by Django 5.1.1 on 2024-11-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_animal_assigned_users_cage_assigned_users_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboxnotification",
            name="sender_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
