# Generated by Django 5.1.1 on 2024-09-16 19:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_strain_experiment"),
    ]

    operations = [
        migrations.AddField(
            model_name="weightmeasurement",
            name="session_timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
