# Generated by Django 4.2.20 on 2025-04-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_submittedpackage_rr_other_info_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="submittedpackage",
            name="attachment_10",
            field=models.FileField(
                blank=True, null=True, upload_to="rr_other_info_attachments/"
            ),
        ),
        migrations.AddField(
            model_name="submittedpackage",
            name="attachment_11",
            field=models.FileField(
                blank=True, null=True, upload_to="rr_other_info_attachments/"
            ),
        ),
        migrations.AddField(
            model_name="submittedpackage",
            name="attachment_12",
            field=models.FileField(
                blank=True, null=True, upload_to="rr_other_info_attachments/"
            ),
        ),
        migrations.AddField(
            model_name="submittedpackage",
            name="attachment_7",
            field=models.FileField(
                blank=True, null=True, upload_to="rr_other_info_attachments/"
            ),
        ),
        migrations.AddField(
            model_name="submittedpackage",
            name="attachment_8",
            field=models.FileField(
                blank=True, null=True, upload_to="rr_other_info_attachments/"
            ),
        ),
        migrations.AddField(
            model_name="submittedpackage",
            name="attachment_9",
            field=models.FileField(
                blank=True, null=True, upload_to="rr_other_info_attachments/"
            ),
        ),
    ]
