# Generated by Django 4.2.17 on 2025-04-15 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_projectattachment_file_hash"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="projectattachment", unique_together={("project", "file_hash")},
        ),
    ]
