# Generated by Django 4.2.17 on 2025-03-01 17:39

import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_pdftemplate_uploaded_pdf_formpackage"),
    ]

    operations = [
        migrations.RemoveField(model_name="formpackage", name="default_form",),
        migrations.RemoveField(model_name="formpackage", name="description",),
        migrations.AddField(
            model_name="formpackage",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="formpackage",
            name="created_by",
            field=models.ForeignKey(
                default=dashboard.models.get_default_user,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="admincreatedform",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name="PackageForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_forms",
                        to="dashboard.formpackage",
                    ),
                ),
                (
                    "pdf_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.pdftemplate",
                    ),
                ),
            ],
            options={"ordering": ["order"],},
        ),
    ]
