# Generated by Django 4.2.20 on 2025-04-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_submittedpackage_attachment_10_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="submittedpackage", name="attachment_10",),
        migrations.RemoveField(model_name="submittedpackage", name="attachment_11",),
        migrations.RemoveField(model_name="submittedpackage", name="attachment_12",),
        migrations.RemoveField(model_name="submittedpackage", name="attachment_7",),
        migrations.RemoveField(model_name="submittedpackage", name="attachment_8",),
        migrations.RemoveField(model_name="submittedpackage", name="attachment_9",),
    ]
