# Generated by Django 4.2.15 on 2024-08-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="default-profile.jpg", upload_to="profile_pictures/"
            ),
        ),
    ]
