# Generated by Django 4.2.17 on 2025-04-15 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_projectattachment_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="projectattachment", unique_together=set(),
        ),
    ]
