# Generated by Django 5.1.1 on 2024-09-16 19:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_weightmeasurement_session_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="weightmeasurement",
            name="session_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
