# Generated by Django 4.2.17 on 2025-04-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_user_position_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("routing_url", models.URLField(blank=True, null=True)),
                (
                    "internal_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("auto_route", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
    ]
