# Generated by Django 5.1.1 on 2024-11-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_inboxnotification_sender_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarevent", name="end_date", field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="calendarevent", name="start_date", field=models.DateTimeField(),
        ),
    ]
