# Generated by Django 4.2.20 on 2025-04-07 18:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_remove_submittedpackage_attachment_10_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rrotherinformation",
            name="animal_welfare_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="rrotherinformation",
            name="environmental_exemption_explanation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="rrotherinformation",
            name="environmental_explanation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="rrotherinformation",
            name="exemption_numbers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=5),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="rrotherinformation",
            name="historic_explanation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="rrotherinformation",
            name="human_assurance_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="rrotherinformation",
            name="iacuc_approval_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rrotherinformation",
            name="international_countries",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="rrotherinformation",
            name="international_explanation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="rrotherinformation",
            name="irb_approval_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
