# Generated by Django 5.1.1 on 2024-11-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_alter_calendarevent_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="all_day",
            field=models.BooleanField(default=False),
        ),
    ]
