# Generated by Django 4.2.17 on 2025-04-16 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_agency"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="agency_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="agency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.agency",
            ),
        ),
    ]
