# Generated by Django 5.1.1 on 2024-09-16 22:32

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_remove_weightmeasurement_session_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="weightmeasurement", name="session",),
        migrations.AddField(
            model_name="weightmeasurement",
            name="session_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="weightmeasurement",
            name="session_timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(name="WeighInSession",),
    ]
