# Generated by Django 4.2.20 on 2025-04-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_rrotherinformation_animal_welfare_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="formpackage", name="package_type",),
        migrations.AddField(
            model_name="packageform",
            name="form_type",
            field=models.CharField(
                choices=[
                    ("sf424", "SF-424"),
                    ("rr_budget", "RR Budget"),
                    ("phs_plan", "PHS Plan"),
                    ("skp", "Senior Key Person"),
                    ("site", "Project Site"),
                    ("rr_other_info", "RR Other Info"),
                    ("phs_cover", "PHS Cover"),
                    ("phs_subjects", "PHS Human Subjects"),
                ],
                default="unknown",
                max_length=100,
            ),
        ),
    ]
