# Generated by Django 4.2.17 on 2025-04-16 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_opportunity_agency_name_alter_opportunity_agency"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="agency_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opportunities",
                to="dashboard.agency",
            ),
        ),  
    ]

