# Generated by Django 5.1.1 on 2024-11-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_calendarevent_all_day"),
    ]

    operations = [
        migrations.RemoveField(model_name="calendarevent", name="completed",),
        migrations.RemoveField(model_name="calendarevent", name="completed_at",),
        migrations.RemoveField(model_name="calendarevent", name="experiment",),
        migrations.RemoveField(model_name="calendarevent", name="specific_dates",),
        migrations.AddField(
            model_name="calendarevent",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="recurrence_days",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="recurrence_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="recurrence_end_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("never", "Never"),
                    ("on", "On Date"),
                    ("after", "After Occurrences"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="recurrence_frequency",
            field=models.CharField(
                blank=True,
                choices=[("week", "Week"), ("month", "Month")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="recurrence_interval",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="recurrence_occurrences",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="color",
            field=models.CharField(default="#1E90FF", max_length=10),
        ),
    ]
