# Generated by Django 5.1.1 on 2024-09-16 23:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_remove_weightmeasurement_session_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="weightmeasurement", name="rfid_assignment",),
        migrations.RemoveField(model_name="weightmeasurement", name="session_id",),
        migrations.AlterField(
            model_name="weightmeasurement",
            name="session_timestamp",
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name="WeighInSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weigh_in_sessions",
                        to="dashboard.experiment",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="weightmeasurement",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="measurements",
                to="dashboard.weighinsession",
            ),
        ),
    ]
