# Generated by Django 5.1.1 on 2024-11-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_remove_calendarevent_completed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarevent",
            name="recurrence_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
