# Generated by Django 4.2.20 on 2025-04-08 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_remove_formpackage_package_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rrotherinformation",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.formpackage",
            ),
        ),
        migrations.AddField(
            model_name="rrotherinformation",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.project",
            ),
        ),
    ]
