# Generated by Django 4.2.15 on 2024-08-19 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_cage_cage_number_cage_experiment"),
    ]

    operations = [
        migrations.AddField(
            model_name="weightmeasurement",
            name="recorder",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="weightmeasurement",
            name="weight_change",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
