# Generated by Django 5.1.1 on 2024-09-16 23:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_remove_weightmeasurement_rfid_assignment_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="weightmeasurement", name="session",),
        migrations.AddField(
            model_name="weightmeasurement",
            name="rfid_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.rfidassignment",
            ),
        ),
        migrations.AddField(
            model_name="weightmeasurement",
            name="session_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name="weightmeasurement",
            name="session_timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(name="WeighInSession",),
    ]
