# Generated by Django 5.1.1 on 2024-11-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_alter_calendarevent_recurrence_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
