# Generated by Django 5.1.1 on 2024-11-12 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_calendarevent_completed_calendarevent_completed_at"),
    ]

    operations = [
        migrations.RemoveField(model_name="calendarevent", name="completed",),
        migrations.RemoveField(model_name="calendarevent", name="completed_at",),
    ]
