# Generated by Django 5.1.1 on 2024-09-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_remove_weightmeasurement_session_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weightmeasurement",
            name="tumor_size_change",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
