# Generated by Django 4.2.15 on 2024-08-20 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_weightmeasurement_recorder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.conversation",
            ),
        ),
    ]
