# Generated by Django 5.1.1 on 2024-09-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_weightmeasurement_tumor_size_change"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_organization_admin",
            field=models.BooleanField(default=False),
        ),
    ]
