# Generated by Django 4.2.15 on 2024-08-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_invitation_conversation"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="invitation_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
