# Generated by Django 4.2.15 on 2024-08-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_message_invitation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rfidassignment",
            name="initial_weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
