# Generated by Django 5.1.1 on 2024-09-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_user_is_organization_admin"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="is_organization_admin",),
    ]
