# Generated by Django 5.1.1 on 2024-11-13 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_calendarevent_is_shared_eventinvitation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventinvitation",
            name="decision_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="eventinvitation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
