# Generated by Django 5.1.1 on 2024-11-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_eventinvitation_decision_date_eventinvitation_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="event_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="user_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
