# Generated by Django 5.1.1 on 2024-09-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_remove_user_is_organization_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="rfid_tag",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
