# Generated by Django 4.2.17 on 2025-04-17 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_alter_project_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Committee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="committees",
                        to="dashboard.organization",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="position_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("app_viewer", "Application Viewer"),
                    ("app_editor", "Application Editor"),
                    ("dept_app_editor", "Department Application Editor"),
                    ("proposal_reviewer", "Proposal Reviewer"),
                    ("dept_app_viewer", "Department Application Viewer"),
                    ("agency_user", "Agency Representative"),
                    ("nih_chair", "NIH Chairperson"),
                    ("nih_board_member", "NIH Board Member"),
                    ("nih_sro", "NIH Scientific Review Officer"),
                ],
                help_text="Defines the specific application-level position",
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="CommitteeMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("chair", "Chairperson"),
                            ("board_member", "Board Member"),
                            ("sro", "Scientific Review Officer"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "committee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="dashboard.committee",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="committee_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("user", "committee")},},
        ),
    ]
