# Generated by Django 4.2.17 on 2025-04-17 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0012_committee_alter_user_position_type_committeemember"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="committeemember", unique_together=set(),),
        migrations.RemoveField(model_name="committee", name="description",),
        migrations.RemoveField(model_name="committee", name="organization",),
        migrations.AddField(
            model_name="committee",
            name="agency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.agency",
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="assigned_reviewers",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"position_type": "nih_sro"},
                related_name="assigned_opportunity_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="committee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opportunities",
                to="dashboard.committee",
            ),
        ),
        migrations.AlterField(
            model_name="committeemember",
            name="role",
            field=models.CharField(
                choices=[
                    ("chair", "Chairperson"),
                    ("board", "Board Member"),
                    ("sro", "Scientific Review Officer"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="committeemember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
