# Generated by Django 4.2.15 on 2024-08-21 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0012_alter_weightmeasurement_recorder_weighin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weightmeasurement",
            name="weigh_in",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.weighin",
            ),
        ),
    ]
