# Generated by Django 4.2.17 on 2025-04-17 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_alter_committeemember_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committee",
            name="agency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="committees",
                to="dashboard.agency",
            ),
        ),
    ]
