# Generated by Django 5.1.1 on 2024-09-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_inboxnotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_organization_admin",
            field=models.BooleanField(default=False),
        ),
    ]
