# Generated by Django 4.2.15 on 2024-08-21 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_alter_weightmeasurement_weigh_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weightmeasurement",
            name="weigh_in",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.weighin",
            ),
        ),
    ]
