# Generated by Django 4.2.17 on 2025-04-18 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_alter_committee_agency"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("factor_1_score", models.IntegerField(blank=True, null=True)),
                ("factor_2_score", models.IntegerField(blank=True, null=True)),
                ("factor_3_comment", models.TextField(blank=True)),
                ("human_subjects", models.TextField(blank=True)),
                ("vertebrate_animals", models.TextField(blank=True)),
                ("biohazards", models.TextField(blank=True)),
                ("resubmission_notes", models.TextField(blank=True)),
                ("authentication", models.TextField(blank=True)),
                ("budget_notes", models.TextField(blank=True)),
                ("overall_score", models.IntegerField(blank=True, null=True)),
                ("overall_justification", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.opportunity",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("user", "project", "opportunity")},},
        ),
    ]
