# Generated by Django 4.2.17 on 2025-03-02 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_alter_formpackage_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="packageform",
            name="html_template_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="formpackage",
            name="created_by",
            field=models.ForeignKey(
                default=django.db.models.query.QuerySet.first,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="packageform",
            name="pdf_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.pdftemplate",
            ),
        ),
    ]
