# Generated by Django 4.2.15 on 2024-08-21 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_alter_weightmeasurement_weigh_in"),
    ]

    operations = [
        migrations.RemoveField(model_name="weightmeasurement", name="weigh_in",),
        migrations.DeleteModel(name="WeighIn",),
    ]
