# Generated by Django 5.1.1 on 2024-11-15 20:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0014_remove_experiment_step_add_investigators_completed_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cage",
            name="allowed_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users allowed to view this cage",
                related_name="allowed_cages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
