# Generated by Django 5.1.1 on 2024-11-16 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0015_cage_allowed_users"),
    ]

    operations = [
        migrations.RenameField(
            model_name="animal", old_name="assigned_users", new_name="allowed_users",
        ),
    ]
