# Generated by Django 5.1.1 on 2024-09-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0015_useraction"),
    ]

    operations = [
        migrations.AddField(
            model_name="weightmeasurement",
            name="valid",
            field=models.BooleanField(default=True),
        ),
    ]
