# Generated by Django 5.1.1 on 2024-09-20 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0016_weightmeasurement_valid"),
    ]

    operations = [
        migrations.RemoveField(model_name="weightmeasurement", name="valid",),
    ]
