# Generated by Django 5.1.1 on 2024-11-16 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0016_rename_assigned_users_animal_allowed_users"),
    ]

    operations = [
        migrations.RenameField(
            model_name="animal", old_name="allowed_users", new_name="assigned_users",
        ),
    ]
