# Generated by Django 5.1.1 on 2024-11-18 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0017_rename_allowed_users_animal_assigned_users"),
    ]

    operations = [
        migrations.RemoveField(model_name="notification", name="recipient",),
        migrations.AddField(
            model_name="notification",
            name="from_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
