# Generated by Django 4.2.17 on 2025-03-03 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0017_alter_formpackage_created_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="performancesitelocation",
            old_name="site_name",
            new_name="street1",
        ),
        migrations.RemoveField(model_name="performancesitelocation", name="address",),
        migrations.AddField(
            model_name="performancesitelocation",
            name="congressional_district",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="performancesitelocation",
            name="county",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="performancesitelocation",
            name="identifier",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="performancesitelocation",
            name="is_individual_submission",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="performancesitelocation",
            name="organization_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="performancesitelocation",
            name="province",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="performancesitelocation",
            name="street2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="performancesitelocation",
            name="uei",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="formpackage",
            name="created_by",
            field=models.ForeignKey(
                default=django.db.models.query.QuerySet.first,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="performancesitelocation",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="performancesitelocation",
            name="zip_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
