# Generated by Django 4.2.17 on 2025-03-03 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0018_rename_site_name_performancesitelocation_street1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formpackage",
            name="created_by",
            field=models.ForeignKey(
                default=django.db.models.query.QuerySet.first,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="RROtherInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proprietary_info", models.BooleanField(default=False)),
                ("environmental_impact", models.BooleanField(default=False)),
                ("historic_properties", models.BooleanField(default=False)),
                (
                    "human_subjects",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=10,
                    ),
                ),
                (
                    "vertebrate_animals",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=10,
                    ),
                ),
                (
                    "international_collaboration",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("no", "No"),
                            ("yes_country", "Yes, with a specific country"),
                            ("yes_global", "Yes, globally"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "uploaded_file",
                    models.FileField(blank=True, null=True, upload_to="rr_other_info/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.organization",
                    ),
                ),
            ],
        ),
    ]
