# Generated by Django 5.1.1 on 2024-11-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0018_remove_notification_recipient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="iv",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
