# Generated by Django 4.2.15 on 2024-08-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0018_experiment_measurement_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="institution",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
