# Generated by Django 4.2.15 on 2024-08-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0019_user_institution_user_location_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="color",
            field=models.CharField(default="blue", max_length=10),
        ),
    ]
