# Generated by Django 5.1.1 on 2024-11-18 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0019_message_iv"),
    ]

    operations = [
        migrations.RemoveField(model_name="message", name="iv",),
    ]
