# Generated by Django 4.2.17 on 2025-04-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0020_costtype_costentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="costtype",
            name="is_idc",
            field=models.BooleanField(default=False),
        ),
    ]
