# Generated by Django 4.2.15 on 2024-08-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0020_calendarevent_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfidassignment",
            name="initial_weight_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
