# Generated by Django 5.1.1 on 2024-11-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0020_remove_message_iv"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="iv",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
