# Generated by Django 4.2.17 on 2025-03-04 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0020_alter_formpackage_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formpackage",
            name="created_by",
            field=models.ForeignKey(
                default=django.db.models.query.QuerySet.first,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="BudgetPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_number",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Budget Period 1"),
                            (2, "Budget Period 2"),
                            (3, "Budget Period 3"),
                            (4, "Budget Period 4"),
                            (5, "Budget Period 5"),
                        ]
                    ),
                ),
                (
                    "uei",
                    models.CharField(
                        max_length=50, verbose_name="Unique Entity Identifier (UEI)"
                    ),
                ),
                (
                    "budget_type",
                    models.CharField(
                        choices=[
                            ("project", "Project"),
                            ("subaward", "Subaward / Consortium"),
                        ],
                        default="project",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_periods",
                        to="dashboard.organization",
                    ),
                ),
            ],
            options={"unique_together": {("organization", "period_number")},},
        ),
    ]
