# Generated by Django 5.1.1 on 2024-11-19 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0021_message_iv"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfidassignment",
            name="simulated_scan",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="weightmeasurement",
            name="input_method",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("rfid", "RFID"),
                    ("simulated", "Simulated"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RFIDScanHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "input_method",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("rfid", "RFID"),
                            ("simulated", "Simulated"),
                        ],
                        default="simulated",
                        max_length=20,
                    ),
                ),
                (
                    "rfid_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.rfidassignment",
                    ),
                ),
                (
                    "scanned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
