# Generated by Django 5.1.1 on 2024-09-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0021_experiment_dashboard_e_name_22f3a2_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="message", name="invitation_id",),
        migrations.AlterField(
            model_name="message",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="attachments/"),
        ),
        migrations.AlterField(
            model_name="message", name="content", field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="message",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
