# Generated by Django 5.1.1 on 2024-09-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0022_remove_message_invitation_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message", name="content", field=models.TextField(),
        ),
    ]
