# Generated by Django 4.2.17 on 2025-03-04 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0022_alter_formpackage_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formpackage",
            name="created_by",
            field=models.ForeignKey(
                default=django.db.models.query.QuerySet.first,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="SeniorKeyPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Mr.", "Mr."),
                            ("Ms.", "Ms."),
                            ("Dr.", "Dr."),
                            ("Prof.", "Prof."),
                            ("Hon.", "Hon."),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(max_length=100)),
                (
                    "suffix",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Jr.", "Jr."),
                            ("Sr.", "Sr."),
                            ("III", "III"),
                            ("IV", "IV"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("base_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "calendar_months",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "academic_months",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "summer_months",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "requested_salary",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "fringe_benefits",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "funds_requested",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("project_role", models.CharField(max_length=255)),
                (
                    "budget_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="senior_key_persons",
                        to="dashboard.budgetperiod",
                    ),
                ),
            ],
        ),
    ]
