# Generated by Django 4.2.17 on 2025-04-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0022_alter_project_principal_investigator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="principal_investigator",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
