# Generated by Django 5.1.1 on 2024-11-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0022_rfidassignment_simulated_scan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfidassignment",
            name="initial_tumor_size",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
