# Generated by Django 4.2.17 on 2025-03-04 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0023_alter_formpackage_created_by_seniorkeyperson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formpackage",
            name="created_by",
            field=models.ForeignKey(
                default=django.db.models.query.QuerySet.first,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="OtherPersonnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("post_doc", "Post Doctoral Associates"),
                            ("grad_student", "Graduate Students"),
                            ("undergrad_student", "Undergraduate Students"),
                            ("clerical", "Secretarial/Clerical"),
                        ],
                        max_length=50,
                    ),
                ),
                ("num_personnel", models.PositiveIntegerField(default=1)),
                ("calendar_months", models.FloatField(default=0.0)),
                ("academic_months", models.FloatField(default=0.0)),
                ("summer_months", models.FloatField(default=0.0)),
                (
                    "requested_salary",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "fringe_benefits",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "budget_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_personnel",
                        to="dashboard.budgetperiod",
                    ),
                ),
            ],
        ),
    ]
