# Generated by Django 5.1.1 on 2024-11-19 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0023_rfidassignment_initial_tumor_size"),
    ]

    operations = [
        migrations.RemoveField(model_name="rfidassignment", name="initial_tumor_size",),
        migrations.RemoveField(model_name="rfidassignment", name="simulated_scan",),
        migrations.RemoveField(model_name="weightmeasurement", name="input_method",),
        migrations.DeleteModel(name="RFIDScanHistory",),
    ]
