# Generated by Django 5.1.1 on 2024-09-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0024_experiment_tumor_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weightmeasurement",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
