# Generated by Django 4.2.17 on 2025-04-23 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0025_project_budget_periods"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectBudgetPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_period_entries",
                        to="dashboard.project",
                    ),
                ),
            ],
        ),
    ]
