# Generated by Django 5.1.1 on 2024-09-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0025_alter_weightmeasurement_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="is_removed",
            field=models.BooleanField(default=False),
        ),
    ]
