# Generated by Django 4.2.15 on 2024-08-28 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0025_observation"),
    ]

    operations = [
        migrations.RemoveField(model_name="animal", name="name",),
        migrations.RemoveField(model_name="observation", name="date_recorded",),
        migrations.AddField(
            model_name="animal",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="animal_index",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="animal",
            name="donor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="ear",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="experiment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.experiment",
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="sex",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="strain",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="tag",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="tail",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="tracking_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="observation",
            name="recorded_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="animal",
            name="species",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="observation",
            name="animal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="observations",
                to="dashboard.animal",
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sample_id", models.CharField(max_length=100)),
                ("sample_type", models.CharField(max_length=100)),
                (
                    "date_collected",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="dashboard.animal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dose", models.CharField(max_length=255)),
                ("stock_concentration", models.CharField(max_length=255)),
                ("dose_volume", models.CharField(max_length=255)),
                (
                    "date_administered",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doses",
                        to="dashboard.animal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
