# Generated by Django 4.2.15 on 2024-08-28 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0026_remove_animal_name_remove_observation_date_recorded_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="dose", old_name="date_administered", new_name="time_recorded",
        ),
        migrations.RenameField(
            model_name="sample", old_name="date_collected", new_name="time_recorded",
        ),
        migrations.AddField(
            model_name="dose",
            name="experiment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.experiment",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sample",
            name="experiment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.experiment",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dose",
            name="animal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.animal"
            ),
        ),
        migrations.AlterField(
            model_name="dose", name="dose", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="dose", name="dose_volume", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="dose", name="stock_concentration", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="sample",
            name="animal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.animal"
            ),
        ),
    ]
