# Generated by Django 5.1.1 on 2024-11-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0027_experiment_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="at_risk",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="animal",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="removal_signature",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="animal",
            name="s_removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="animal",
            name="tracking_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
