# Generated by Django 5.1.1 on 2024-09-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0027_animal_removal_signature_usersignature"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraction",
            name="typed_signature",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="useraction",
            name="unique_signature",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
