# Generated by Django 5.1.1 on 2024-11-20 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0028_animal_at_risk_animal_is_available_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="animal", name="at_risk",),
        migrations.RemoveField(model_name="animal", name="donor",),
        migrations.RemoveField(model_name="animal", name="ear",),
        migrations.RemoveField(model_name="animal", name="is_available",),
        migrations.RemoveField(model_name="animal", name="removal_signature",),
        migrations.RemoveField(model_name="animal", name="removed",),
        migrations.RemoveField(model_name="animal", name="s_removed",),
        migrations.RemoveField(model_name="animal", name="tag",),
        migrations.RemoveField(model_name="animal", name="tracking_date",),
        migrations.RemoveField(model_name="experiment", name="duration",),
    ]
