# Generated by Django 4.2.15 on 2024-08-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0028_alter_animal_animal_index_alter_animal_experiment"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="animal", unique_together={("experiment", "animal_index")},
        ),
    ]
