# Generated by Django 5.1.1 on 2024-09-24 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0028_useraction_typed_signature_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboxnotification",
            name="from_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="inboxnotification",
            name="experiment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.experiment",
            ),
        ),
    ]
