# Generated by Django 4.2.17 on 2025-03-05 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0029_delete_rr_budgetform_alter_formpackage_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formpackage",
            name="created_by",
            field=models.ForeignKey(
                default=django.db.models.query.QuerySet.first,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="SF424Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submission_type",
                    models.CharField(
                        choices=[
                            ("preapplication", "Preapplication"),
                            ("application", "Application"),
                            ("correction", "Changed/Corrected Application"),
                        ],
                        max_length=100,
                    ),
                ),
                ("date_submitted", models.DateField()),
                (
                    "applicant_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "state_application_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "federal_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("contact_first_name", models.CharField(max_length=100)),
                ("contact_last_name", models.CharField(max_length=100)),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "total_federal_funds_requested",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "total_non_federal_funds",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
