# Generated by Django 5.1.1 on 2024-11-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0029_remove_animal_at_risk_remove_animal_donor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="removed",
            field=models.BooleanField(default=False),
        ),
    ]
