# Generated by Django 4.2.15 on 2024-08-29 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0029_animal_removed_alter_animal_unique_together"),
    ]

    operations = [
        migrations.RemoveField(model_name="weightmeasurement", name="animal_index",),
        migrations.RemoveField(model_name="weightmeasurement", name="experiment",),
        migrations.AddField(
            model_name="weightmeasurement",
            name="animal",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.animal",
            ),
        ),
    ]
