# Generated by Django 5.1.1 on 2024-11-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0030_animal_is_available_animal_removed"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="duration",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
