# Generated by Django 4.2.15 on 2024-08-29 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0030_remove_weightmeasurement_animal_index_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="rfidassignment", name="animal_index",),
        migrations.AddField(
            model_name="rfidassignment",
            name="animal",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.animal",
            ),
        ),
        migrations.AddField(
            model_name="weightmeasurement",
            name="rfid_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.rfidassignment",
            ),
        ),
        migrations.AlterField(
            model_name="weightmeasurement",
            name="animal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.animal"
            ),
        ),
    ]
