# Generated by Django 4.2.17 on 2025-03-05 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0030_alter_formpackage_created_by_sf424form"),
    ]

    operations = [
        migrations.CreateModel(
            name="SF424Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_submission", models.CharField(max_length=50)),
                ("date_submitted", models.DateField()),
                (
                    "applicant_identifier",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_received_state", models.DateField(blank=True, null=True)),
                (
                    "state_application_identifier",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "federal_identifier",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("legal_name", models.CharField(max_length=255)),
                ("street_address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=20)),
                ("employer_identification", models.CharField(max_length=100)),
                ("type_of_applicant", models.CharField(max_length=100)),
                ("type_of_application", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="formpackage",
            name="created_by",
            field=models.ForeignKey(
                default=django.db.models.query.QuerySet.first,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
