# Generated by Django 4.2.15 on 2024-08-29 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0031_remove_rfidassignment_animal_index_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rfidassignment",
            name="animal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.animal"
            ),
        ),
    ]
