# Generated by Django 5.1.1 on 2024-09-28 00:04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0031_signedform"),
    ]

    operations = [
        migrations.AddField(
            model_name="signedform",
            name="reviewed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="signedform",
            name="file_path",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="signedform",
            name="signed_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="signedform",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
