# Generated by Django 4.2.17 on 2025-03-06 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0031_sf424submission_alter_formpackage_created_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sf424submission",
            old_name="street_address",
            new_name="address_street1",
        ),
        migrations.RenameField(
            model_name="sf424submission",
            old_name="federal_identifier",
            new_name="agency_routing_number",
        ),
        migrations.RenameField(
            model_name="sf424submission",
            old_name="type_submission",
            new_name="contact_phone",
        ),
        migrations.RenameField(
            model_name="sf424submission",
            old_name="employer_identification",
            new_name="country",
        ),
        migrations.RenameField(
            model_name="sf424submission",
            old_name="state_application_identifier",
            new_name="federal_entity_identifier",
        ),
        migrations.RenameField(
            model_name="sf424submission",
            old_name="type_of_applicant",
            new_name="submission_type",
        ),
        migrations.RemoveField(
            model_name="sf424submission", name="date_received_state",
        ),
        migrations.RemoveField(
            model_name="sf424submission", name="type_of_application",
        ),
        migrations.AddField(
            model_name="sf424submission",
            name="address_street2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sf424submission",
            name="consolidated_app",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sf424submission",
            name="contact_email",
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name="sf424submission",
            name="contact_name",
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name="sf424submission",
            name="date_created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="sf424submission",
            name="duns_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sf424submission",
            name="ein_tin",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sf424submission",
            name="explanation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sf424submission",
            name="previous_tracking_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sf424submission",
            name="state_use_only",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="formpackage",
            name="created_by",
            field=models.ForeignKey(
                default=django.db.models.query.QuerySet.first,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
