# Generated by Django 4.2.15 on 2024-08-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0032_alter_rfidassignment_animal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rfidassignment",
            name="rfid",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="rfidassignment", unique_together={("experiment", "animal")},
        ),
    ]
