# Generated by Django 5.1.1 on 2024-09-29 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0033_adminform_admincreatedform_signedadminform_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="admincreatedform", old_name="form_name", new_name="name",
        ),
        migrations.AlterField(
            model_name="admincreatedform",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="FormField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_label", models.CharField(max_length=255)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Input"),
                            ("textarea", "Text Area"),
                            ("date", "Date"),
                            ("yes_no", "Yes/No Question"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="dashboard.admincreatedform",
                    ),
                ),
            ],
        ),
    ]
