# Generated by Django 4.2.17 on 2025-04-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0033_projectbudgetperiod_budget_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeentry",
            name="cost_type",
            field=models.CharField(
                choices=[
                    ("direct", "Direct Personnel Cost"),
                    ("indirect", "Indirect Personnel Cost"),
                ],
                default="direct",
                max_length=10,
            ),
        ),
    ]
