# Generated by Django 4.2.15 on 2024-08-29 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0033_alter_rfidassignment_rfid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="observation", old_name="name", new_name="category",
        ),
    ]
