# Generated by Django 5.1.1 on 2024-11-20 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0034_experiment_monitor_tumor_experiment_monitor_weight"),
    ]

    operations = [
        migrations.RemoveField(model_name="animal", name="at_risk",),
        migrations.RemoveField(model_name="animal", name="duration",),
        migrations.RemoveField(model_name="animal", name="is_available",),
        migrations.RemoveField(model_name="animal", name="removed",),
        migrations.RemoveField(model_name="experiment", name="duration",),
        migrations.RemoveField(model_name="experiment", name="monitor_tumor",),
        migrations.RemoveField(model_name="experiment", name="monitor_weight",),
    ]
