# Generated by Django 5.1.1 on 2024-09-29 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0034_rename_form_name_admincreatedform_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="signedform", name="form_name",),
        migrations.AddField(
            model_name="signedform",
            name="form",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.admincreatedform",
            ),
        ),
        migrations.AlterField(
            model_name="signedform",
            name="signed_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
