# Generated by Django 4.2.15 on 2024-08-29 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0034_rename_name_observation_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sample", old_name="time_recorded", new_name="timestamp",
        ),
        migrations.AlterField(
            model_name="sample",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
