# Generated by Django 4.2.17 on 2025-04-25 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0034_employeeentry_cost_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("personnel", "Personnel"),
                            ("non_personnel", "Non-Personnel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subcategory", models.CharField(max_length=100)),
                (
                    "budget_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_allocations",
                        to="dashboard.fund",
                    ),
                ),
            ],
            options={"unique_together": {("fund", "period_start", "subcategory")},},
        ),
    ]
