# Generated by Django 5.1.1 on 2024-09-29 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0035_remove_signedform_form_name_signedform_form_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signedform",
            name="form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.admincreatedform",
            ),
        ),
    ]
