# Generated by Django 4.2.15 on 2024-08-29 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0035_rename_time_recorded_sample_timestamp_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dose", old_name="time_recorded", new_name="timestamp",
        ),
        migrations.AddField(
            model_name="dose",
            name="drug_name",
            field=models.CharField(default="Unknown Drug", max_length=100),
        ),
        migrations.AlterField(
            model_name="dose",
            name="dose",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="dose",
            name="dose_volume",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="dose",
            name="stock_concentration",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="dose",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
