# Generated by Django 5.1.1 on 2024-09-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0036_alter_signedform_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="formfield",
            name="choices",
            field=models.TextField(blank=True, null=True),
        ),
    ]
