# Generated by Django 4.2.15 on 2024-08-29 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0036_rename_time_recorded_dose_timestamp_dose_drug_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="rfidassignment",
            name="animal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rfid_assignments",
                to="dashboard.animal",
            ),
        ),
    ]
