# Generated by Django 5.1.1 on 2024-09-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0037_formfield_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text Input"),
                    ("textarea", "Text Area"),
                    ("date", "Date"),
                    ("yes_no", "Yes/No Question"),
                    ("multiple_choice", "Multiple Choice"),
                ],
                max_length=50,
            ),
        ),
    ]
