# Generated by Django 5.1.1 on 2024-11-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0037_experiment_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="at_risk",
            field=models.BooleanField(default=False),
        ),
    ]
