# Generated by Django 4.2.15 on 2024-08-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0038_remove_experiment_number_of_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cage",
            name="number",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
