# Generated by Django 5.1.1 on 2024-09-29 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0038_alter_formfield_field_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signedform",
            name="form",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.admincreatedform",
            ),
        ),
    ]
