# Generated by Django 5.1.1 on 2024-11-21 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0038_animal_at_risk"),
    ]

    operations = [
        migrations.RemoveField(model_name="animal", name="at_risk",),
        migrations.RemoveField(model_name="animal", name="removed",),
        migrations.RemoveField(model_name="experiment", name="duration",),
    ]
