# Generated by Django 4.2.17 on 2025-03-17 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0038_alter_formpackage_created_by_submittedpackage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formpackage",
            name="created_by",
            field=models.ForeignKey(
                default=django.db.models.query.QuerySet.first,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="submittedpackage",
            name="budget_periods",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="submittedpackage",
            name="cumulative_totals",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="submittedpackage",
            name="sf424_data",
            field=models.JSONField(default=dict),
        ),
    ]
