# Generated by Django 5.1.1 on 2024-09-29 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0039_alter_signedform_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="signedform",
            name="digital_signature",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="signedform",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.admincreatedform",
            ),
        ),
    ]
