# Generated by Django 5.1.1 on 2024-11-21 16:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0039_remove_animal_at_risk_remove_animal_removed_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="rfidassignment", name="dashboard_r_rfid_5d6a03_idx",
        ),
        migrations.RemoveIndex(
            model_name="weightmeasurement", name="dashboard_w_timesta_84f532_idx",
        ),
        migrations.RemoveIndex(
            model_name="weightmeasurement", name="dashboard_w_weight_2348fb_idx",
        ),
        migrations.RemoveIndex(
            model_name="weightmeasurement", name="dashboard_w_tumor_s_2cfda1_idx",
        ),
        migrations.RemoveField(model_name="treatment", name="unit",),
        migrations.AddField(
            model_name="animal",
            name="assigned_users",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_animals", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="at_risk",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="animal",
            name="donor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="ear",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="fur_color",
            field=models.CharField(default="", max_length=7),
        ),
        migrations.AddField(
            model_name="animal",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="removal_signature",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="animal",
            name="tag",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="tail",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="tracking_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="animal",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="animal",
            name="cage",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="animals",
                to="dashboard.cage",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="experiment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.experiment",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.group",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="True if assigned to an experiment, otherwise False",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.organization",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="rfidassignment",
            name="experiment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.experiment",
            ),
        ),
        migrations.AlterField(
            model_name="rfidassignment",
            name="rfid",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="weightmeasurement",
            name="animal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.animal"
            ),
        ),
        migrations.AlterField(
            model_name="weightmeasurement",
            name="recorder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="weightmeasurement",
            name="rfid_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.rfidassignment",
            ),
        ),
        migrations.AlterField(
            model_name="weightmeasurement",
            name="session_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name="weightmeasurement",
            name="tumor_size",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="weightmeasurement",
            name="tumor_size_change",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="weightmeasurement",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="weightmeasurement",
            name="weight_change",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
