# Generated by Django 5.1.1 on 2024-10-01 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0041_organization_alter_user_institution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="dashboard.organization",
            ),
        ),
    ]
