# Generated by Django 5.1.1 on 2024-10-01 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0042_conversation_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.organization",
            ),
        ),
    ]
