# Generated by Django 4.2.17 on 2025-04-28 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0042_costentry_is_reference"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref_num1", models.CharField(max_length=100)),
                ("ref_num2", models.CharField(blank=True, max_length=100, null=True)),
                ("code", models.CharField(blank=True, max_length=100, null=True)),
                ("vendor", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cost_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="dashboard.costtype",
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="dashboard.fund",
                    ),
                ),
            ],
            options={"unique_together": {("fund", "ref_num1", "cost_type")},},
        ),
    ]
