# Generated by Django 4.2.17 on 2025-04-28 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0043_reference"),
    ]

    operations = [
        migrations.DeleteModel(name="Reference",),
    ]
