# Generated by Django 4.2.17 on 2025-03-20 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0043_submittedpackage_cover_letter_attachment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submittedpackage", name="cover_letter_attachment",
        ),
        migrations.RemoveField(
            model_name="submittedpackage", name="pre_application_attachment",
        ),
        migrations.RemoveField(model_name="submittedpackage", name="sflll_attachment",),
        migrations.AddField(
            model_name="submittedpackage",
            name="attachments",
            field=models.ManyToManyField(
                blank=True, related_name="submitted_packages", to="dashboard.attachment"
            ),
        ),
        migrations.AlterField(
            model_name="formpackage",
            name="created_by",
            field=models.ForeignKey(
                default=django.db.models.query.QuerySet.first,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
