# Generated by Django 5.1.1 on 2024-10-02 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0044_inboxnotification_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.organization",
            ),
        ),
    ]
