# Generated by Django 4.2.17 on 2025-04-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0045_user_dark_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hover_color",
            field=models.CharField(
                blank=True,
                help_text="User-specific hover color (e.g., #e1cd10)",
                max_length=7,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="sidebar_color",
            field=models.CharField(
                blank=True,
                help_text="User-specific sidebar color (e.g., #115600)",
                max_length=7,
                null=True,
            ),
        ),
    ]
