# Generated by Django 4.2.15 on 2024-09-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0045_experiment_ended"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="message_attachments/"
            ),
        ),
    ]
