# Generated by Django 5.1.1 on 2024-10-02 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0046_admincreatedform_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraction",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.organization",
            ),
        ),
    ]
