# Generated by Django 4.2.15 on 2024-09-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0046_message_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
