# Generated by Django 4.2.17 on 2025-04-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0046_user_hover_color_user_sidebar_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="friend",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
