# Generated by Django 4.2.17 on 2025-05-01 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0047_friend_created_at"),
    ]

    operations = [
        migrations.RemoveField(model_name="conversation", name="organization",),
    ]
