# Generated by Django 5.1.1 on 2024-10-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0047_useraction_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="admincreatedform",
            name="header",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="admincreatedform",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="form_logos/"),
        ),
        migrations.AddField(
            model_name="admincreatedform",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
