# Generated by Django 5.1.1 on 2024-10-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0048_admincreatedform_header_admincreatedform_logo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminPDFTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("pdf_file", models.FileField(upload_to="pdf_templates/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
