# Generated by Django 4.2.17 on 2025-05-02 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0048_remove_conversation_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="linked_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.projecttask",
            ),
        ),
    ]
