# Generated by Django 5.1.1 on 2024-11-24 22:43

from django.db import migrations, models
import os

def populate_iv(apps, schema_editor):
    """
    Populate the `iv` column with random IVs for existing rows where `iv` is NULL.
    """
    Message = apps.get_model("dashboard", "Message")
    for message in Message.objects.filter(iv__isnull=True):
        # Generate a random IV (16 bytes for AES-256)
        message.iv = os.urandom(16)
        message.save(update_fields=["iv"])

class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0049_experiment_custom_interval_days_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_iv),  # Data migration step
        migrations.AlterField(
            model_name="message",
            name="iv",
            field=models.BinaryField(),
        ),
    ]
