# Generated by Django 5.1.1 on 2024-10-07 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0050_pdftemplate"),
    ]

    operations = [
        migrations.RemoveField(model_name="pdftemplate", name="header",),
        migrations.RemoveField(model_name="pdftemplate", name="logo",),
        migrations.RemoveField(model_name="pdftemplate", name="subtitle",),
        migrations.AddField(
            model_name="formfield",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="form_fields",
                to="dashboard.pdftemplate",
            ),
        ),
        migrations.AddField(
            model_name="pdftemplate",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.organization",
            ),
        ),
        migrations.AlterField(
            model_name="pdftemplate",
            name="description",
            field=models.TextField(default="No description provided"),
        ),
        migrations.AlterField(
            model_name="pdftemplate",
            name="uploaded_pdf",
            field=models.FileField(
                default="pdf_templates/default.pdf", upload_to="pdf_templates/"
            ),
        ),
    ]
