# Generated by Django 5.1.1 on 2024-11-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0051_alter_experiment_tumor_size_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_banner",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_banners/"
            ),
        ),
    ]
