# Generated by Django 5.1.1 on 2024-10-07 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0051_remove_pdftemplate_header_remove_pdftemplate_logo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="signedform",
            name="pdf_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.pdftemplate",
            ),
        ),
        migrations.AlterField(
            model_name="signedform",
            name="form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.admincreatedform",
            ),
        ),
    ]
