# Generated by Django 4.2.17 on 2025-05-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0051_project_organization"),
    ]

    operations = [
        migrations.RemoveField(model_name="calendarevent", name="created_by",),
        migrations.RemoveField(model_name="calendarevent", name="linked_task",),
        migrations.RemoveField(model_name="project", name="organization",),
    ]
