# Generated by Django 4.2.17 on 2025-05-02 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0052_remove_calendarevent_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="project_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calendar_events",
                to="dashboard.projecttask",
            ),
        ),
    ]
