# Generated by Django 5.1.1 on 2024-11-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0052_user_profile_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="iv",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
