# Generated by Django 5.1.1 on 2024-10-07 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0052_signedform_pdf_template_alter_signedform_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdftemplate",
            name="header",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pdftemplate",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="pdf_logos/"),
        ),
        migrations.AddField(
            model_name="pdftemplate",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="pdftemplate", name="description", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="pdftemplate",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.organization"
            ),
        ),
        migrations.AlterField(
            model_name="pdftemplate",
            name="uploaded_pdf",
            field=models.FileField(upload_to="pdf_templates/"),
        ),
    ]
