# Generated by Django 4.2.17 on 2025-03-21 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0052_project_alter_formpackage_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_identifier",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="formpackage",
            name="created_by",
            field=models.ForeignKey(
                default=django.db.models.query.QuerySet.first,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
