# Generated by Django 4.2.17 on 2025-05-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0053_calendarevent_project_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("es", "Spanish")],
                default="en",
                help_text="User's preferred language (e.g., en, es)",
                max_length=10,
            ),
        ),
    ]
