# Generated by Django 5.1.1 on 2024-10-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0053_pdftemplate_header_pdftemplate_logo_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="pdftemplate", name="header",),
        migrations.RemoveField(model_name="pdftemplate", name="logo",),
        migrations.RemoveField(model_name="pdftemplate", name="subtitle",),
        migrations.AddField(
            model_name="pdftemplate",
            name="editable_fields",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
