# Generated by Django 5.1.1 on 2024-11-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0053_alter_message_content_alter_message_iv"),
    ]

    operations = [
        migrations.RemoveField(model_name="message", name="event_id",),
        migrations.RemoveField(model_name="message", name="iv",),
        migrations.RemoveField(model_name="message", name="user_id",),
        migrations.AlterField(
            model_name="message", name="content", field=models.TextField(null=True),
        ),
    ]
