# Generated by Django 5.1.1 on 2024-10-07 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0054_remove_pdftemplate_header_remove_pdftemplate_logo_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFFieldMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=255)),
                ("editable", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pdf_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_mappings",
                        to="dashboard.pdftemplate",
                    ),
                ),
            ],
        ),
    ]
