# Generated by Django 5.1.1 on 2024-11-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0054_remove_message_event_id_remove_message_iv_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="event_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="iv",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="user_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
