# Generated by Django 4.2.17 on 2025-05-05 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0055_organization_idc_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="IACUCSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "protocol_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("protocol_title", models.CharField(max_length=255)),
                ("species", models.CharField(max_length=255)),
                ("procedures", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "upload",
                    models.FileField(blank=True, null=True, upload_to="iacuc_uploads/"),
                ),
                ("status", models.CharField(default="Submitted", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="iacuc_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.organization",
                    ),
                ),
                (
                    "principal_investigator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="iacuc_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
