# Generated by Django 5.1.1 on 2024-10-07 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0055_pdffieldmapping"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pdffieldmapping", old_name="editable", new_name="is_editable",
        ),
    ]
