# Generated by Django 5.1.1 on 2024-11-29 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0055_message_event_id_message_iv_message_user_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_system_message",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
