# Generated by Django 5.1.1 on 2024-10-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0056_rename_editable_pdffieldmapping_is_editable"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdffieldmapping",
            name="height",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="pdffieldmapping",
            name="width",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="pdffieldmapping",
            name="x",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="pdffieldmapping",
            name="y",
            field=models.FloatField(default=0.0),
        ),
    ]
