# Generated by Django 4.2.17 on 2025-05-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0056_iacucsubmission"),
    ]

    operations = [
        migrations.RemoveField(model_name="iacucsubmission", name="protocol_number",),
        migrations.RemoveField(model_name="iacucsubmission", name="status",),
        migrations.AddField(
            model_name="iacucsubmission",
            name="document_status",
            field=models.CharField(default="In Progress", max_length=100),
        ),
        migrations.AddField(
            model_name="iacucsubmission",
            name="document_type",
            field=models.CharField(default="Standard IACUC", max_length=100),
        ),
        migrations.AddField(
            model_name="iacucsubmission",
            name="involves_vertebrate_animals",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="iacucsubmission",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="iacucsubmission",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="iacucsubmission",
            name="procedures",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="iacucsubmission",
            name="species",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="iacucsubmission",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
