# Generated by Django 5.1.1 on 2024-12-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0057_conversationuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rfidassignment",
            name="cage_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
