# Generated by Django 5.1.1 on 2024-10-08 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0057_pdffieldmapping_height_pdffieldmapping_width_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdffieldmapping",
            name="form_field",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.formfield",
            ),
            preserve_default=False,
        ),
    ]
