# Generated by Django 4.2.17 on 2025-03-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0057_alter_formpackage_created_by"),
    ]

    operations = [
        migrations.RemoveField(model_name="formpackage", name="created_by",),
        migrations.AddField(
            model_name="formpackage",
            name="package_type",
            field=models.CharField(
                choices=[
                    ("rr_budget", "RR Budget Only"),
                    ("sf424", "SF-424 Only"),
                    ("combined", "Combined (RR Budget + SF-424)"),
                ],
                default="combined",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="formpackage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="formpackage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="formpackage",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
