# Generated by Django 4.2.17 on 2025-05-05 14:43

import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0058_remove_iacucsubmission_end_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="iacucsubmission", name="created_by",),
        migrations.RemoveField(model_name="iacucsubmission", name="document_status",),
        migrations.RemoveField(model_name="iacucsubmission", name="document_type",),
        migrations.RemoveField(model_name="iacucsubmission", name="organization",),
        migrations.RemoveField(model_name="iacucsubmission", name="upload",),
        migrations.AddField(
            model_name="iacucsubmission",
            name="user",
            field=models.ForeignKey(
                default=dashboard.models.get_default_user,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="iacucsubmission",
            name="involves_vertebrate_animals",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="iacucsubmission",
            name="principal_investigator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="iacuc_pi",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
