# Generated by Django 5.1.1 on 2024-10-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0058_pdffieldmapping_form_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="color",
            field=models.CharField(default="orange", max_length=10),
        ),
    ]
