# Generated by Django 4.2.17 on 2025-03-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0058_remove_formpackage_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="formpackage", name="created_at",),
        migrations.RemoveField(model_name="formpackage", name="organization",),
        migrations.RemoveField(model_name="formpackage", name="updated_at",),
        migrations.AlterField(
            model_name="formpackage",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="formpackage",
            name="package_type",
            field=models.CharField(
                choices=[
                    ("rr_budget", "RR Budget Only"),
                    ("sf424", "SF-424 Only"),
                    ("combined", "Combined (RR Budget + SF-424)"),
                ],
                max_length=20,
            ),
        ),
    ]
