# Generated by Django 5.1.1 on 2024-12-04 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0059_attachment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attachment", old_name="timestamp", new_name="uploaded_at",
        ),
        migrations.RemoveField(model_name="attachment", name="uploaded_by",),
    ]
