# Generated by Django 5.1.1 on 2024-10-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0059_calendarevent_completed_alter_calendarevent_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="color",
            field=models.CharField(default="blue", max_length=10),
        ),
    ]
