# Generated by Django 4.2.17 on 2025-03-21 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0059_remove_formpackage_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formpackage",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.organization",
            ),
        ),
    ]
