# Generated by Django 5.1.1 on 2024-12-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0060_rename_timestamp_attachment_uploaded_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
