# Generated by Django 4.2.17 on 2025-05-05 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0060_iacucsubmission_external_collaboration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IACUCProtocolSpecies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("species_name", models.CharField(max_length=100)),
                ("breeding", models.BooleanField(default=False)),
                ("procedures", models.BooleanField(default=False)),
                ("restraint", models.BooleanField(default=False)),
                ("surgery", models.BooleanField(default=False)),
                ("vet_drugs", models.BooleanField(default=False)),
                ("test_agents", models.BooleanField(default=False)),
                ("euthanize", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="species_entries",
                        to="dashboard.iacucsubmission",
                    ),
                ),
            ],
        ),
    ]
