# Generated by Django 4.2.17 on 2025-03-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0060_formpackage_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="submittedpackage",
            name="project_id",
            field=models.IntegerField(default=0),
        ),
    ]
