# Generated by Django 4.2.17 on 2025-03-22 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0061_submittedpackage_project_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="submittedpackage", name="project_id",),
    ]
