# Generated by Django 5.1.1 on 2024-10-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0063_eventcompletion"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="at_risk",
            field=models.BooleanField(default=False),
        ),
    ]
