# Generated by Django 5.1.1 on 2024-12-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0063_experiment_bulk_upload_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
