# Generated by Django 4.2.17 on 2025-03-22 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0063_opportunity_form_package"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.project",
            ),
        ),
    ]
