# Generated by Django 5.1.1 on 2024-12-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0064_alter_message_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="attachment_mime_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
