# Generated by Django 5.1.1 on 2024-12-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0064_alter_message_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="message", name="is_system_message",),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
