# Generated by Django 4.2.17 on 2025-05-05 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0064_iacucinternalfundingsource"),
    ]

    operations = [
        migrations.CreateModel(
            name="IACUCPrivateFundingSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("fund_title", models.CharField(max_length=255)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="private_funding_sources",
                        to="dashboard.iacucsubmission",
                    ),
                ),
            ],
        ),
    ]
