# Generated by Django 5.1.1 on 2024-12-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0065_remove_message_is_system_message_alter_message_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="attachment_mime_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
