# Generated by Django 4.2.17 on 2025-03-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0065_submittedpackage_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="is_added",
            field=models.BooleanField(default=False),
        ),
    ]
