# Generated by Django 4.2.17 on 2025-03-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0066_opportunity_is_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="admin_unit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="instrument_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="prime_sponsor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="project_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="project_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="sponsor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="sponsor_deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="total_sponsor_costs",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
