# Generated by Django 5.1.1 on 2024-12-11 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0066_experiment_session_active_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="weightmeasurement", unique_together={("animal", "session_id")},
        ),
    ]
