# Generated by Django 5.1.1 on 2024-10-10 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0066_remove_task_assigned_to_alter_task_experiment"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="cage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.cage",
            ),
        ),
    ]
