# Generated by Django 4.2.17 on 2025-05-05 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0067_externalcollaboration"),
    ]

    operations = [
        migrations.CreateModel(
            name="OffCampusWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collaborator_name", models.CharField(max_length=255)),
                ("site_location", models.CharField(max_length=255)),
                ("assurance_number", models.CharField(max_length=255)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="off_campus_works",
                        to="dashboard.iacucsubmission",
                    ),
                ),
            ],
        ),
    ]
