# Generated by Django 4.2.17 on 2025-03-22 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0067_opportunity_admin_unit_opportunity_instrument_type_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="opportunity", name="admin_unit",),
        migrations.RemoveField(model_name="opportunity", name="instrument_type",),
        migrations.RemoveField(model_name="opportunity", name="prime_sponsor",),
        migrations.RemoveField(model_name="opportunity", name="project_end_date",),
        migrations.RemoveField(model_name="opportunity", name="project_start_date",),
        migrations.RemoveField(model_name="opportunity", name="sponsor",),
        migrations.RemoveField(model_name="opportunity", name="sponsor_deadline",),
        migrations.RemoveField(model_name="opportunity", name="total_sponsor_costs",),
    ]
