# Generated by Django 5.1.1 on 2024-10-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0067_animal_cage"),
    ]

    operations = [
        migrations.RemoveField(model_name="message", name="is_read",),
        migrations.AddField(
            model_name="message",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
