# Generated by Django 5.1.1 on 2024-12-11 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0067_alter_weightmeasurement_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="weightmeasurement",
            unique_together={("animal", "weight", "timestamp")},
        ),
    ]
