# Generated by Django 4.2.17 on 2025-03-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0068_remove_opportunity_admin_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="admin_unit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="instrument_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="prime_sponsor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="principal_investigator",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="project_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="project_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="sponsor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="sponsor_deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="total_sponsor_costs",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
