# Generated by Django 4.2.17 on 2025-05-05 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0068_offcampuswork"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutsideHousing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("under_24hrs", models.BooleanField(default=False)),
                ("under_24hrs_location", models.CharField(blank=True, max_length=255)),
                ("under_24hrs_justification", models.TextField(blank=True)),
                ("over_24hrs", models.BooleanField(default=False)),
                ("over_24hrs_location", models.CharField(blank=True, max_length=255)),
                ("over_24hrs_justification", models.TextField(blank=True)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outside_housing",
                        to="dashboard.iacucsubmission",
                    ),
                ),
            ],
        ),
    ]
