# Generated by Django 5.1.1 on 2024-12-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0068_alter_weightmeasurement_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraction",
            name="session_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
