# Generated by Django 4.2.17 on 2025-03-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0069_project_admin_unit_project_instrument_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submittedpackage",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
    ]
