# Generated by Django 4.2.17 on 2025-05-05 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0069_outsidehousing"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicTransportUse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("following_policy", models.BooleanField(default=True)),
                ("justification", models.TextField(blank=True)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_transport",
                        to="dashboard.iacucsubmission",
                    ),
                ),
            ],
        ),
    ]
