# Generated by Django 5.1.1 on 2024-10-15 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0069_message_is_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.organization",
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="type",
            field=models.CharField(
                choices=[("private", "Private"), ("group", "Group")],
                default="private",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="user1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations_user1",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="user2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations_user2",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
