# Generated by Django 5.1.1 on 2024-10-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0070_alter_conversation_organization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friend",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("accepted", "Accepted")],
                default="pending",
                max_length=10,
            ),
        ),
    ]
