# Generated by Django 4.2.17 on 2025-03-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0070_submittedpackage_is_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="submittedpackage",
            name="rr_budget_data",
            field=models.JSONField(default=dict),
        ),
    ]
