# Generated by Django 4.2.17 on 2025-03-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0071_submittedpackage_rr_budget_data"),
    ]

    operations = [
        migrations.RemoveField(model_name="performancesitelocation", name="uei",),
    ]
