# Generated by Django 5.1.1 on 2024-10-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0071_alter_friend_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="group_profile_pictures/"
            ),
        ),
    ]
