# Generated by Django 5.1.1 on 2024-12-13 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0071_remove_experiment_investigators_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="task", name="due_date",),
        migrations.RemoveField(model_name="task", name="duration",),
        migrations.RemoveField(model_name="task", name="frequency",),
        migrations.AddField(
            model_name="calendarevent",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calendar_events",
                to="dashboard.task",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="days_of_week",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="task",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
