# Generated by Django 5.1.1 on 2024-10-17 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0072_conversation_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(model_name="admincreatedform", name="header",),
        migrations.RemoveField(model_name="admincreatedform", name="logo",),
        migrations.RemoveField(model_name="admincreatedform", name="subtitle",),
        migrations.AddField(
            model_name="admincreatedform",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.pdftemplate",
            ),
        ),
        migrations.AlterField(
            model_name="admincreatedform",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.organization",
            ),
        ),
    ]
