# Generated by Django 5.1.1 on 2024-12-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0072_remove_task_due_date_remove_task_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="recurrence_days",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="task",
            name="recurrence_frequency",
            field=models.CharField(
                choices=[("weeks", "Weeks"), ("months", "Months")],
                default="weeks",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="recurrence_interval",
            field=models.IntegerField(default=1),
        ),
    ]
