# Generated by Django 4.2.17 on 2025-03-23 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0072_remove_performancesitelocation_uei"),
    ]

    operations = [
        migrations.RemoveField(model_name="budgetperiod", name="uei",),
    ]
