# Generated by Django 4.2.17 on 2025-03-24 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0073_remove_budgetperiod_uei"),
    ]

    operations = [
        migrations.AddField(
            model_name="submittedpackage",
            name="opportunity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.opportunity",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="submittedpackage",
            unique_together={
                ("user", "org_id", "package_id", "project", "opportunity", "is_draft")
            },
        ),
    ]
