# Generated by Django 5.1.1 on 2024-10-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0073_remove_admincreatedform_header_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="signedform",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="signedform",
            name="is_high_importance",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="signedform",
            name="file_path",
            field=models.FileField(upload_to="signed_forms/"),
        ),
    ]
