# Generated by Django 5.1.1 on 2024-12-13 21:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0073_task_recurrence_days_task_recurrence_frequency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed_by",
            field=models.ManyToManyField(
                blank=True, related_name="completed_tasks", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="requires_individual_completion",
            field=models.BooleanField(default=False),
        ),
    ]
