# Generated by Django 4.2.17 on 2025-03-27 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0074_submittedpackage_opportunity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
