# Generated by Django 5.1.1 on 2024-10-17 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0074_signedform_is_anonymous_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signedadminform",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
