# Generated by Django 4.2.17 on 2025-05-05 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0074_fieldsafetyprecautions"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldStudyPermit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("permits_required", models.BooleanField(default=False)),
                ("permit_details", models.TextField(blank=True)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_permits",
                        to="dashboard.iacucsubmission",
                    ),
                ),
            ],
        ),
    ]
