# Generated by Django 4.2.17 on 2025-03-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0075_project_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="project", name="org_id", field=models.IntegerField(default=1),
        ),
    ]
