# Generated by Django 5.1.1 on 2024-12-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0075_task_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
