# Generated by Django 5.1.1 on 2024-10-17 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0075_alter_signedadminform_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="signedform", name="digital_signature",),
        migrations.RemoveField(model_name="signedform", name="pdf_template",),
        migrations.RemoveField(model_name="signedform", name="reviewed",),
        migrations.AlterField(
            model_name="signedform",
            name="form",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.admincreatedform",
            ),
            preserve_default=False,
        ),
    ]
