# Generated by Django 5.1.1 on 2024-12-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0076_calendarevent_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="public",
                max_length=10,
            ),
        ),
    ]
