# Generated by Django 5.1.1 on 2024-10-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0076_remove_signedform_digital_signature_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("principal_admin", "Principal Admin"),
                    ("admin", "Admin"),
                    ("officer", "Officer"),
                    ("researcher", "Researcher"),
                    ("viewer", "Viewer"),
                ],
                default="viewer",
                max_length=20,
            ),
        ),
    ]
