# Generated by Django 5.1.1 on 2024-12-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0077_user_profile_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
