# Generated by Django 4.2.17 on 2025-03-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0077_projecttask"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttask",
            name="task_category",
            field=models.CharField(
                choices=[
                    ("planning", "Planning"),
                    ("execution", "Execution"),
                    ("testing", "Testing"),
                    ("review", "Review"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="projecttask",
            name="task_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="projecttask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("development", "Development"),
                    ("research", "Research"),
                    ("analysis", "Analysis"),
                    ("documentation", "Documentation"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
