# Generated by Django 4.2.17 on 2025-05-06 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0077_speciesprocedure"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeciesRestraint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "restraint_type",
                    models.CharField(
                        choices=[
                            ("chronic", "Chronic"),
                            ("prolonged", "Prolonged"),
                            ("routine", "Routine"),
                            ("specialized", "Specialized"),
                        ],
                        max_length=20,
                    ),
                ),
                ("rationale", models.TextField()),
                ("duration", models.CharField(max_length=255)),
                ("acclimation", models.TextField()),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restraint_entry",
                        to="dashboard.iacucprotocolspecies",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="species_restraint_forms",
                        to="dashboard.iacucsubmission",
                    ),
                ),
            ],
            options={"unique_together": {("submission", "species")},},
        ),
    ]
