# Generated by Django 4.2.17 on 2025-03-28 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0078_projecttask_task_category_projecttask_task_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttask",
            name="status",
            field=models.CharField(
                choices=[("in_progress", "In Progress"), ("completed", "Completed")],
                default="in_progress",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="projecttask",
            name="task_completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projecttask_completed_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
