# Generated by Django 5.1.1 on 2024-10-18 01:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0078_remove_task_created_at_remove_task_is_completed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
