# Generated by Django 4.2.17 on 2024-12-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0078_user_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="organization_logos/"
            ),
        ),
    ]
