# Generated by Django 4.2.17 on 2024-12-28 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0079_organization_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboxnotification",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.organization",
            ),
        ),
        migrations.AddField(
            model_name="inboxnotification",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
