# Generated by Django 4.2.17 on 2025-05-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0079_speciessurgery"),
    ]

    operations = [
        migrations.AddField(
            model_name="speciessurgery",
            name="analgesics_withheld",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="speciessurgery",
            name="clinical_parameters",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="speciessurgery",
            name="monitoring_plan",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="speciessurgery",
            name="pre_op_procedures",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="speciessurgery",
            name="support_anesthesia",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="speciessurgery",
            name="surgical_attire",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="speciessurgery",
            name="suture_removal_timing",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
