# Generated by Django 4.2.17 on 2024-12-29 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0080_inboxnotification_organization_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="conversation", name="user1",),
        migrations.RemoveField(model_name="conversation", name="user2",),
        migrations.AddField(
            model_name="conversation",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="member_conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
