# Generated by Django 4.2.17 on 2025-03-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0080_taskcomment_taskattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(default="Development", max_length=50),
        ),
    ]
