# Generated by Django 4.2.17 on 2024-12-29 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0081_remove_conversation_user1_remove_conversation_user2_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="conversation", name="members",),
        migrations.AddField(
            model_name="conversation",
            name="user1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations_user1",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="user2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations_user2",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
