# Generated by Django 4.2.17 on 2025-05-06 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0081_speciessurgery_surgery_location_building_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeciesMSS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("multiple_surgeries", models.BooleanField(default=False)),
                ("surgery_description", models.TextField(blank=True)),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.iacucprotocolspecies",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.iacucsubmission",
                    ),
                ),
            ],
            options={"unique_together": {("submission", "species")},},
        ),
    ]
