# Generated by Django 5.1.1 on 2024-10-18 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0081_alter_task_due_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="taskreminder", name="recipient",),
        migrations.AddField(
            model_name="taskreminder",
            name="recipient",
            field=models.ManyToManyField(
                related_name="received_tasks", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
