# Generated by Django 4.2.17 on 2025-03-28 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0081_project_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="routing_users",
            field=models.ManyToManyField(
                blank=True, related_name="routing_projects", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="RoutingDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("approve", "Approve"),
                            ("reject", "Send Back to Development"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("decision_date", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routing_decisions",
                        to="dashboard.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
