# Generated by Django 4.2.17 on 2025-03-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0082_project_routing_users_routingdecision"),
    ]

    operations = [
        migrations.AddField(
            model_name="routingdecision",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="routingdecision",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("approved", "Approved"),
                    ("declined", "Declined"),
                ],
                default="waiting",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("Development", "Development"),
                    ("Under Review", "Under Review"),
                    ("Approved", "Approved"),
                ],
                default="Development",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="routingdecision",
            name="decision",
            field=models.CharField(
                blank=True,
                choices=[("approve", "Approve"), ("reject", "Reject")],
                max_length=50,
                null=True,
            ),
        ),
    ]
