# Generated by Django 5.1.1 on 2024-10-18 14:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0082_remove_taskreminder_recipient_taskreminder_recipient"),
    ]

    operations = [
        migrations.RemoveField(model_name="taskupdate", name="task",),
        migrations.RemoveField(model_name="taskupdate", name="updated_by",),
        migrations.RemoveField(model_name="task", name="assigned_to",),
        migrations.RemoveField(model_name="task", name="due_date",),
        migrations.RemoveField(model_name="task", name="notes",),
        migrations.RemoveField(model_name="task", name="status",),
        migrations.AddField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(name="TaskReminder",),
        migrations.DeleteModel(name="TaskUpdate",),
    ]
