# Generated by Django 4.2.17 on 2025-05-06 18:29

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0083_speciesvetdrug"),
    ]

    operations = [
        migrations.CreateModel(
            name="HazardousAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("agent_name", models.CharField(max_length=200)),
                ("committee_number", models.CharField(blank=True, max_length=100)),
                (
                    "route_admin",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("IM", "IM"),
                                ("INH", "INH"),
                                ("INJ", "INJ"),
                                ("IP", "IP"),
                                ("IV", "IV"),
                                ("ORL", "ORL"),
                                ("SQ", "SQ"),
                                ("TCP", "TCP"),
                                ("TOP", "TOP"),
                            ],
                            max_length=10,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("other_route", models.CharField(blank=True, max_length=100)),
                ("volume_frequency", models.CharField(max_length=200)),
                ("duration", models.CharField(max_length=200)),
                ("brought_into_facility", models.BooleanField(default=False)),
                ("precautions", models.TextField()),
                ("is_pharma_grade", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.iacucprotocolspecies",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.iacucsubmission",
                    ),
                ),
            ],
        ),
    ]
