# Generated by Django 4.2.17 on 2024-12-29 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0083_conversation_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="mute_notifications",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who have muted this conversation",
                related_name="muted_conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
