# Generated by Django 4.2.17 on 2025-01-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0084_conversation_mute_notifications"),
    ]

    operations = [
        migrations.RemoveField(model_name="message", name="event_id",),
        migrations.RemoveField(model_name="message", name="user_id",),
        migrations.AddField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[("text", "Text"), ("attachment", "Attachment")],
                default="text",
                max_length=20,
            ),
        ),
    ]
