# Generated by Django 5.1.1 on 2024-10-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0085_experiment_description_experiment_start_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="calendarevent", name="color",),
        migrations.AddField(
            model_name="calendarevent",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="calendarevent", name="end_date", field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="calendarevent", name="start_date", field=models.DateTimeField(),
        ),
    ]
