# Generated by Django 4.2.17 on 2025-01-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0085_remove_message_event_id_remove_message_user_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="message", name="message_type",),
        migrations.AddField(
            model_name="message",
            name="event_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="user_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
