# Generated by Django 4.2.17 on 2025-05-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0085_specieseuthanasia"),
    ]

    operations = [
        migrations.AddField(
            model_name="specieseuthanasia",
            name="num_b",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="specieseuthanasia",
            name="num_c",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="specieseuthanasia",
            name="num_d",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="specieseuthanasia",
            name="num_e",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
