# Generated by Django 4.2.17 on 2025-01-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0086_remove_message_message_type_message_event_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
        ),
    ]
