# Generated by Django 4.2.17 on 2025-03-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0086_projectattachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectattachment",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="project_attachments/"
            ),
        ),
    ]
