# Generated by Django 5.1.1 on 2024-10-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0087_alter_experiment_number_of_animals"),
    ]

    operations = [
        migrations.RemoveField(model_name="calendarevent", name="description",),
        migrations.RemoveField(model_name="experiment", name="description",),
        migrations.RemoveField(model_name="experiment", name="start_date",),
        migrations.AddField(
            model_name="calendarevent",
            name="color",
            field=models.CharField(default="blue", max_length=10),
        ),
        migrations.AlterField(
            model_name="calendarevent", name="end_date", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="calendarevent", name="start_date", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='number_of_animals',
            field=models.IntegerField(default=0),  # Provide a default value here
        )
    ]