# Generated by Django 4.2.17 on 2025-01-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0087_message_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="thumbnail_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
