# Generated by Django 4.2.17 on 2025-03-29 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0087_alter_projectattachment_file"),
    ]

    operations = [
        migrations.DeleteModel(name="ProjectAttachment",),
    ]
