# Generated by Django 4.2.17 on 2025-05-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0087_specieseuthanasia_euthanasia_criteria_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="specieseuthanasia",
            name="exemptions_justification",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="specieseuthanasia",
            name="food_water_restriction",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="specieseuthanasia",
            name="husbandry_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="specieseuthanasia",
            name="requesting_exemptions",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="specieseuthanasia",
            name="restriction_justification",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="specieseuthanasia",
            name="special_husbandry",
            field=models.BooleanField(default=False),
        ),
    ]
