# Generated by Django 4.2.17 on 2025-05-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0088_specieseuthanasia_exemptions_justification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="specieseuthanasia",
            name="reduce_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="specieseuthanasia",
            name="refine_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="specieseuthanasia",
            name="replace_description",
            field=models.TextField(blank=True),
        ),
    ]
