# Generated by Django 4.2.17 on 2025-01-04 00:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0088_message_thumbnail_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="mute_notifications",
            field=models.ManyToManyField(
                blank=True,
                db_index=True,
                help_text="Users who have muted this conversation",
                related_name="muted_conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="name",
            field=models.CharField(
                blank=True, default="Unnamed Group", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="default-group-profile.jpg",
                null=True,
                upload_to="group_profile_pictures/",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["type"], name="dashboard_c_type_083765_idx"),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["organization"], name="dashboard_c_organiz_7d238b_idx"
            ),
        ),
    ]
