# Generated by Django 4.2.17 on 2025-01-04 02:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0089_alter_conversation_mute_notifications_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="conversation", name="dashboard_c_type_083765_idx",
        ),
        migrations.RemoveIndex(
            model_name="conversation", name="dashboard_c_organiz_7d238b_idx",
        ),
        migrations.AlterField(
            model_name="conversation",
            name="mute_notifications",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who have muted this conversation",
                related_name="muted_conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="group_profile_pictures/"
            ),
        ),
    ]
