# Generated by Django 4.2.17 on 2025-03-30 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0089_projectattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="submittedpackage",
            name="last_edited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="edited_drafts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
