# Generated by Django 4.2.17 on 2025-01-04 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0090_remove_conversation_dashboard_c_type_083765_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmember",
            name="role",
            field=models.CharField(
                choices=[("member", "Member"), ("admin", "Admin")],
                default="member",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="conversation_members",
                through="dashboard.GroupMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_members",
                to="dashboard.conversation",
            ),
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
