# Generated by Django 4.2.17 on 2025-03-30 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0090_submittedpackage_last_edited_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submittedpackage",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
