# Generated by Django 4.2.17 on 2025-05-06 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0090_specieseuthanasia_adverse_reactions_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatabaseSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("animals_in_pain_d_or_e", models.BooleanField()),
                ("databases_used", models.TextField(blank=True)),
                ("search_terms", models.TextField(blank=True)),
                ("consultations", models.TextField(blank=True)),
                ("journals", models.TextField(blank=True)),
                ("scientific_meetings", models.TextField(blank=True)),
                ("alternatives_reason", models.TextField(blank=True)),
                ("search_date", models.DateField(blank=True, null=True)),
                ("years_covered", models.CharField(blank=True, max_length=50)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="database_search",
                        to="dashboard.iacucsubmission",
                    ),
                ),
            ],
        ),
    ]
