# Generated by Django 4.2.17 on 2025-01-04 18:02

from django.conf import settings
from django.db import migrations, models
from django.db.utils import ProgrammingError

class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0091_groupmember_role_alter_conversation_members_and_more"),
    ]

    def safely_remove_members(apps, schema_editor):
        """Safely remove the 'members' column if it exists."""
        try:
            schema_editor.execute("ALTER TABLE dashboard_conversation DROP COLUMN members;")
        except ProgrammingError:
            # The column doesn't exist; ignore the error.
            pass

    operations = [
        migrations.RunPython(safely_remove_members),  # Replace RemoveField with this
        migrations.AddField(
            model_name="conversation",
            name="members_new",
            field=models.ManyToManyField(
                blank=True,
                related_name="conversation_members_new",
                through="dashboard.GroupMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]