# Generated by Django 4.2.17 on 2025-01-04 18:02
from django.db import migrations

def migrate_members_to_new_field(apps, schema_editor):
    Conversation = apps.get_model('dashboard', 'Conversation')
    GroupMember = apps.get_model('dashboard', 'GroupMember')

    for conversation in Conversation.objects.filter(type='group'):
        for user in conversation.members.all():
            GroupMember.objects.create(conversation=conversation, user=user)

class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0092_remove_conversation_members_conversation_members_new"),
    ]

    operations = [
        migrations.RunPython(migrate_members_to_new_field),
    ]