# Generated by Django 4.2.17 on 2025-03-31 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0092_projectaccess"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="agency",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="cfda",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="close_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="comp_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="comp_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="open_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="package_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="title",
            field=models.CharField(default="Untitled Opportunity", max_length=255),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="form_package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.formpackage",
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="number",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="number_of_periods",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="organization",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="principal_investigator",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.project",
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="proposal_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
