# Generated by Django 4.2.17 on 2025-01-04 18:06

from django.db import migrations, models


def copy_members_to_group_members(apps, schema_editor):
    """Copy existing members from the old members field to the new GroupMember model."""
    Conversation = apps.get_model('dashboard', 'Conversation')
    GroupMember = apps.get_model('dashboard', 'GroupMember')
    User = apps.get_model('auth', 'User')

    # Migrate group members to GroupMember
    for conversation in Conversation.objects.filter(type='group'):
        for user in conversation.members_new.all():
            GroupMember.objects.get_or_create(conversation=conversation, user=user)


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0093_auto_20250104_1302"),  # Update with the correct previous migration
    ]

    operations = [
        # Remove the old ManyToManyField
        migrations.RemoveField(
            model_name="conversation",
            name="members",
        ),
        # Add new ManyToManyField with through
        migrations.AddField(
            model_name="conversation",
            name="members_new",
            field=models.ManyToManyField(
                blank=True,
                related_name="conversation_members_new",
                through="dashboard.GroupMember",
                to="auth.user",
            ),
        ),
        # Run a data migration to populate GroupMember
        migrations.RunPython(copy_members_to_group_members),
    ]
