# Generated by Django 4.2.17 on 2025-05-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0093_iacucsubmission_end_date_iacucsubmission_procedures_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="iacucsubmission", name="end_date",),
        migrations.RemoveField(model_name="iacucsubmission", name="procedures",),
        migrations.RemoveField(model_name="iacucsubmission", name="species",),
        migrations.RemoveField(model_name="iacucsubmission", name="start_date",),
        migrations.RemoveField(model_name="iacucsubmission", name="upload",),
    ]
