# Generated by Django 4.2.17 on 2025-05-07 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0094_remove_iacucsubmission_end_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IRBSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("protocol_title", models.CharField(max_length=255)),
                ("human_subjects_involved", models.BooleanField(default=False)),
                ("summary", models.TextField(blank=True)),
                ("risks", models.TextField(blank=True)),
                ("consent_procedures", models.TextField(blank=True)),
                ("submission_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("In Review", "In Review"),
                            ("Approved", "Approved"),
                            ("Returned", "Returned"),
                        ],
                        default="Draft",
                        max_length=30,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
