# Generated by Django 4.2.17 on 2025-01-04 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0094_auto_20250104_1306"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="members_new",
            field=models.ManyToManyField(
                blank=True,
                related_name="conversation_members_new",
                through="dashboard.GroupMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
