# Generated by Django 4.2.17 on 2025-03-31 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0094_projectopportunity"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="attached_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="attached_opportunities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
