# Generated by Django 5.1.1 on 2024-10-22 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0094_treatment"),
    ]

    operations = [
        migrations.RemoveField(model_name="group", name="drug",),
        migrations.RemoveField(model_name="group", name="strain",),
        migrations.AddField(
            model_name="group",
            name="color",
            field=models.CharField(default="#FFFFFF", max_length=7),
        ),
        migrations.AddField(
            model_name="group",
            name="treatment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="group_treatment",
                to="dashboard.treatment",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="number_of_animals",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="treatments_for_group",
                to="dashboard.group",
            ),
        ),
    ]
