# Generated by Django 4.2.17 on 2025-03-31 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0095_opportunity_attached_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="submittedpackage",
            name="finalized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
