# Generated by Django 4.2.17 on 2025-01-04 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0095_alter_conversation_members_new"),
    ]

    operations = [
        migrations.RemoveField(model_name="conversation", name="members_new",),
        migrations.RemoveField(model_name="groupmember", name="role",),
        migrations.AddField(
            model_name="conversation",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="conversation_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groupmember",
                to="dashboard.conversation",
            ),
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
