# Generated by Django 5.1.1 on 2024-10-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0095_remove_group_drug_remove_group_strain_group_color_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="timezone",
            field=models.CharField(default="EST", max_length=50),
        ),
    ]
