# Generated by Django 4.2.17 on 2025-04-02 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0096_submittedpackage_finalized_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="PHSResearchPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_id", models.IntegerField()),
                (
                    "introductionAttachment",
                    models.FileField(
                        blank=True, null=True, upload_to="phs_attachments/"
                    ),
                ),
                (
                    "specificAimsAttachment",
                    models.FileField(
                        blank=True, null=True, upload_to="phs_attachments/"
                    ),
                ),
                (
                    "researchStrategyAttachment",
                    models.FileField(
                        blank=True, null=True, upload_to="phs_attachments/"
                    ),
                ),
                (
                    "progressReportPublicationList",
                    models.FileField(
                        blank=True, null=True, upload_to="phs_attachments/"
                    ),
                ),
                (
                    "protectionHumanSubjectsAttachment",
                    models.FileField(
                        blank=True, null=True, upload_to="phs_attachments/"
                    ),
                ),
                (
                    "inclusionWomenMinoritiesAttachment",
                    models.FileField(
                        blank=True, null=True, upload_to="phs_attachments/"
                    ),
                ),
                (
                    "targetedPlannedEnrollmentAttachment",
                    models.FileField(
                        blank=True, null=True, upload_to="phs_attachments/"
                    ),
                ),
                (
                    "inclusionEnrollmentReportAttachment",
                    models.FileField(
                        blank=True, null=True, upload_to="phs_attachments/"
                    ),
                ),
                (
                    "vertebrateAnimalsAttachment",
                    models.FileField(
                        blank=True, null=True, upload_to="phs_attachments/"
                    ),
                ),
                (
                    "selectAgentResearchAttachment",
                    models.FileField(
                        blank=True, null=True, upload_to="phs_attachments/"
                    ),
                ),
                (
                    "multiplePDPILeadershipPlan",
                    models.FileField(
                        blank=True, null=True, upload_to="phs_attachments/"
                    ),
                ),
                (
                    "consortiumContractualArrangements",
                    models.FileField(
                        blank=True, null=True, upload_to="phs_attachments/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phs_plans",
                        to="dashboard.project",
                    ),
                ),
            ],
        ),
    ]
