# Generated by Django 4.2.17 on 2025-05-07 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0097_remove_irbsubmission_study_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="irbsubmission",
            name="funding_additional_info",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="IRBFundingSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=255)),
                ("sponsor", models.CharField(blank=True, max_length=255)),
                ("sponsor_number", models.CharField(blank=True, max_length=100)),
                (
                    "pi",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_sources",
                        to="dashboard.irbsubmission",
                    ),
                ),
            ],
        ),
    ]
