# Generated by Django 4.2.17 on 2025-04-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0097_phsresearchplan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formpackage",
            name="package_type",
            field=models.CharField(
                choices=[
                    ("rr_budget", "RR Budget Only"),
                    ("sf424", "SF-424 Only"),
                    ("combined", "Combined (RR Budget + SF-424)"),
                    ("phs_only", "PHS Only"),
                ],
                max_length=20,
            ),
        ),
    ]
