# Generated by Django 4.2.17 on 2025-01-04 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0097_remove_conversation_members_conversation_members_new_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="message", name="user_id",),
    ]
