# Generated by Django 4.2.17 on 2025-04-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0098_alter_formpackage_package_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="submittedpackage",
            name="phs_plan_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
