# Generated by Django 5.1.1 on 2024-10-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0098_rename_step_groups_completed_experiment_step_add_investigators_completed_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="task", old_name="assigned_to", new_name="assignees",
        ),
        migrations.AddField(
            model_name="task", name="duration", field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="task", name="frequency", field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
