# Generated by Django 4.2.17 on 2025-05-07 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0098_irbsubmission_funding_additional_info_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IRBStudyMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PI", "Principal Investigator"),
                            ("Co-Investigator", "Co-Investigator"),
                            ("Research Coordinator", "Research Coordinator"),
                            ("Other Staff", "Other Study Staff"),
                            ("Grad Student", "Graduate Student Investigator"),
                            ("Undergrad Student", "Undergraduate Student Investigator"),
                            ("Study Physician", "Study Physician"),
                            ("Study Nurse", "Study Nurse"),
                        ],
                        max_length=50,
                    ),
                ),
                ("involved_in_consent", models.BooleanField()),
                ("has_financial_interest", models.BooleanField()),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.irbsubmission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
