# Generated by Django 4.2.17 on 2025-01-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0098_remove_message_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="user_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
