# Generated by Django 4.2.17 on 2025-04-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0099_submittedpackage_phs_plan_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="submittedpackage",
            name="senior_key_person_data",
            field=models.JSONField(default=dict),
        ),
    ]
