# Generated by Django 4.2.17 on 2025-01-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0098_remove_message_user_id"),  # Ensure this is the correct dependency
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="iv",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="attachment_mime_type",
            field=models.CharField(max_length=255, blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="thumbnail",
            field=models.ImageField(upload_to="thumbnails/", blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="thumbnail_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="event_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="is_system_message",
            field=models.BooleanField(default=False),
        ),
        # The `user_id` field already exists in this migration; no need to add it again.
    ]