# Generated by Django 4.2.17 on 2025-05-07 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0099_irbstudymember"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="irbstudymember", name="has_financial_interest",
        ),
        migrations.AddField(
            model_name="irbstudymember",
            name="financial_interest",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="irbstudymember",
            name="involved_in_consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="irbstudymember",
            name="role",
            field=models.CharField(
                choices=[
                    ("PI", "Principal Investigator"),
                    ("Co-Investigator", "Co-Investigator"),
                    ("Coordinator", "Research Coordinator"),
                    ("Staff", "Other Study Staff"),
                    ("Grad Student", "Graduate Student Investigator"),
                    ("Undergrad", "Undergrad Student Investigator"),
                    ("Physician", "Study Physician"),
                    ("Nurse", "Study Nurse"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="irbstudymember",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="dashboard.irbsubmission",
            ),
        ),
        migrations.AlterField(
            model_name="irbstudymember",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
