# Generated by Django 4.2.17 on 2025-01-04 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0099_message_user_id"),
        ("dashboard", "0100_message_user_id"),
    ]

    operations = []
