# Generated by Django 4.2.17 on 2025-04-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0100_submittedpackage_senior_key_person_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submittedpackage",
            name="senior_key_person_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
