# Generated by Django 4.2.17 on 2025-04-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0101_alter_submittedpackage_senior_key_person_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="submittedpackage",
            name="phs_cover_page_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
