# Generated by Django 4.2.17 on 2025-05-07 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0101_irbstudylocation"),
    ]

    operations = [
        migrations.CreateModel(
            name="IRBDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("Consent", "Consent Form"),
                            ("Recruitment", "Recruitment Material"),
                            ("Other", "Other Attachment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("version", models.CharField(max_length=50)),
                ("file", models.FileField(upload_to="irb_documents/")),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Survey Questionaire", "Survey Questionaire"),
                            ("Screening Form", "Screening Form"),
                            ("Data Collection Form", "Data Collection Form"),
                            ("Contract/ Agreement", "Contract/ Agreement"),
                            ("Grant", "Grant"),
                            ("Site Authorization", "Site Authorization"),
                            ("Training Document", "Training Document"),
                            ("Product Labels / Brochure", "Product Labels / Brochure"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("category_description", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="dashboard.irbsubmission",
                    ),
                ),
            ],
        ),
    ]
