# Generated by Django 4.2.17 on 2025-01-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0101_merge_0099_message_user_id_0100_message_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
