# Generated by Django 5.1.1 on 2024-10-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0101_remove_experiment_investigators_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
