# Generated by Django 4.2.17 on 2025-01-05 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("dashboard", "0102_user_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboxnotification",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="inboxnotification",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inboxnotification",
            name="priority",
            field=models.CharField(
                choices=[
                    ("info", "Information"),
                    ("warning", "Warning"),
                    ("critical", "Critical"),
                ],
                default="info",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="inboxnotification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
