# Generated by Django 4.2.17 on 2025-05-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0102_irbdocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="irbsubmission",
            name="funding_additional_info",
            field=models.TextField(blank=True, null=True),
        ),
    ]
