# Generated by Django 5.1.1 on 2024-10-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0102_calendarevent_description"),
    ]

    operations = [
        migrations.RemoveField(model_name="group", name="treatment",),
        migrations.AlterField(
            model_name="group", name="number_of_animals", field=models.IntegerField(),
        ),
    ]
