# Generated by Django 4.2.17 on 2025-04-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0102_submittedpackage_phs_cover_page_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submittedpackage",
            name="senior_key_person_data",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
