# Generated by Django 5.1.1 on 2024-10-24 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0103_remove_group_treatment_alter_group_number_of_animals"),
    ]

    operations = [
        migrations.RemoveField(model_name="treatment", name="group",),
        migrations.AddField(
            model_name="group",
            name="treatment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.treatment",
            ),
        ),
    ]
