# Generated by Django 5.1.1 on 2024-10-24 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0104_remove_treatment_group_group_treatment"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.group",
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="treatments",
            field=models.ManyToManyField(
                blank=True, related_name="animals", to="dashboard.treatment"
            ),
        ),
    ]
