# Generated by Django 4.2.17 on 2025-01-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0104_mutedconversation"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="is_muted",
            field=models.BooleanField(default=False),
        ),
    ]
