# Generated by Django 5.1.1 on 2024-10-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0105_animal_group_animal_treatments"),
    ]

    operations = [
        migrations.CreateModel(
            name="RFID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rfid", models.CharField(max_length=100, unique=True)),
                ("assigned", models.BooleanField(default=False)),
            ],
        ),
    ]
