# Generated by Django 4.2.17 on 2025-01-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0105_conversation_is_muted"),
    ]

    operations = [
        migrations.RemoveField(model_name="conversation", name="is_muted",),
    ]
