# Generated by Django 4.2.17 on 2025-05-08 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0105_remove_irbsubmission_exclusion_criteria_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IRBStudyDrug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generic_name", models.CharField(max_length=255)),
                ("brand_name", models.CharField(max_length=255)),
                (
                    "drug_type",
                    models.CharField(
                        choices=[
                            ("Drug", "Drug"),
                            ("Biologic", "Biologic"),
                            ("Food Product", "Food Product"),
                            ("Dietary Supplement", "Dietary Supplement"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "other_type_description",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_drugs",
                        to="dashboard.irbsubmission",
                    ),
                ),
            ],
        ),
    ]
