# Generated by Django 5.1.1 on 2024-10-28 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0106_rfid"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="fur_color",
            field=models.CharField(default="black", max_length=7),
        ),
        migrations.AlterField(
            model_name="animal",
            name="experiment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.experiment",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female")],
                max_length=10,
                null=True,
            ),
        ),
    ]
