# Generated by Django 4.2.17 on 2025-01-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0106_remove_conversation_is_muted"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mute_all_notifications",
            field=models.BooleanField(
                default=False, help_text="Mute all incoming notifications for this user"
            ),
        ),
    ]
