# Generated by Django 4.2.17 on 2025-05-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0106_irbstudydrug"),
    ]

    operations = [
        migrations.AddField(
            model_name="irbsubmission",
            name="ind_numbers",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="irbsubmission",
            name="under_fda_ind",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
