# Generated by Django 4.2.17 on 2025-05-08 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0107_irbsubmission_ind_numbers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IRBStudyDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_name", models.CharField(max_length=255)),
                ("is_humanitarian_use", models.BooleanField(default=False)),
                (
                    "exemption_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("IDE", "IDE"),
                            (
                                "Abbreviated IDE",
                                "Claim of Abbreviated IDE (Nonsignificant Risk Device)",
                            ),
                            ("Exempt", "Exempt from IDE Requirements"),
                            ("Not Applicable", "Not Applicable"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "evaluates_safety_effectiveness",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_devices",
                        to="dashboard.irbsubmission",
                    ),
                ),
            ],
        ),
    ]
