# Generated by Django 4.2.17 on 2025-01-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0107_user_mute_all_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="read_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
