# Generated by Django 5.1.1 on 2024-10-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0107_animal_date_of_birth_animal_fur_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="fur_color",
            field=models.CharField(default="", max_length=7),
        ),
    ]
