# Generated by Django 5.1.1 on 2024-10-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0108_alter_animal_fur_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="animal_index",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="animal",
            name="cage",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
