# Generated by Django 4.2.17 on 2025-01-08 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0108_message_read_timestamp"),
    ]

    operations = [
        migrations.RemoveField(model_name="conversationuser", name="conversation",),
        migrations.RemoveField(model_name="conversationuser", name="last_deleted_at",),
    ]
