# Generated by Django 5.1.1 on 2024-10-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0109_alter_animal_animal_index_alter_animal_cage"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="cage_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
