# Generated by Django 4.2.17 on 2025-05-08 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0109_irbsubmission_device_exemption_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="irbsubmission",
            name="coordinator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coordinated_irb_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
