# Generated by Django 4.2.17 on 2025-01-08 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0109_remove_conversationuser_conversation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationuser",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.conversation",
            ),
        ),
        migrations.AddField(
            model_name="conversationuser",
            name="last_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
