# Generated by Django 4.2.17 on 2025-05-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0110_irbsubmission_coordinator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="irbsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Pre Submission", "Pre Submission"),
                    ("In Review", "In Review"),
                    ("Approved", "Approved"),
                    ("Returned", "Returned"),
                ],
                default="Draft",
                max_length=30,
            ),
        ),
    ]
