# Generated by Django 5.1.1 on 2024-10-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0110_animal_cage_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="animal",
            name="is_inactive",
            field=models.BooleanField(default=False),
        ),
    ]
