# Generated by Django 4.2.17 on 2025-01-08 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0110_conversationuser_conversation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversationuser",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="dashboard.conversation",
            ),
        ),
    ]
