# Generated by Django 5.1.1 on 2024-10-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0111_animal_is_active_animal_is_inactive"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animal", options={"ordering": ["animal_index"]},
        ),
        migrations.AlterUniqueTogether(
            name="animal", unique_together={("organization", "rfid_tag")},
        ),
        migrations.AlterField(
            model_name="animal",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="True if assigned to an experiment, otherwise False",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="rfid_tag",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.RemoveField(model_name="animal", name="is_inactive",),
    ]
