# Generated by Django 4.2.17 on 2025-01-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0111_alter_conversationuser_conversation"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="hover_color",
            field=models.CharField(default="#e1cd10", max_length=7),
        ),
        migrations.AddField(
            model_name="organization",
            name="sidebar_color",
            field=models.CharField(default="#115600", max_length=7),
        ),
    ]
