# Generated by Django 4.2.17 on 2025-01-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0112_organization_hover_color_organization_sidebar_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dashboard_layout",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
