# Generated by Django 5.1.1 on 2024-10-29 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0112_alter_animal_options_alter_animal_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cage",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cages",
                to="dashboard.organization",
            ),
        ),
    ]
