# Generated by Django 5.1.1 on 2024-10-29 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0113_cage_organization"),
    ]

    operations = [
        migrations.RemoveField(model_name="cage", name="number",),
    ]
