# Generated by Django 4.2.17 on 2025-05-09 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0113_alter_irbsubmission_status_iacuccommittee"),
    ]

    operations = [
        migrations.CreateModel(
            name="IACUCMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("veterinarian", "Veterinarian"),
                            ("scientist", "Animal Research Scientist"),
                            ("non_scientist", "Non-Scientist"),
                            ("community_member", "Community Member"),
                            ("chair", "IACUC Chair"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                (
                    "committee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="dashboard.iacuccommittee",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="iacuc_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("committee", "user")},},
        ),
    ]
