# Generated by Django 5.1.1 on 2024-10-29 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0114_remove_cage_number"),
    ]

    operations = [
        migrations.RemoveField(model_name="animal", name="cage_id",),
        migrations.AlterField(
            model_name="animal",
            name="cage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="animals",
                to="dashboard.cage",
            ),
        ),
    ]
