# Generated by Django 4.2.17 on 2025-05-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0114_iacucmember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iacucmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("veterinarian", "Veterinarian"),
                    ("scientist", "Animal Research Scientist"),
                    ("non_scientist", "Non-Scientist"),
                    ("community_member", "Community Member"),
                    ("chair", "IACUC Chair"),
                    ("office_member", "IACUC Office Member"),
                ],
                max_length=30,
            ),
        ),
    ]
