# Generated by Django 5.1.1 on 2024-10-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0116_alter_animal_cage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="cage",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
