# Generated by Django 4.2.17 on 2025-01-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0118_message_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="primary_color",
            field=models.CharField(default="#000000", max_length=7),
        ),
        migrations.AddField(
            model_name="organization",
            name="secondary_color",
            field=models.CharField(default="#FFFFFF", max_length=7),
        ),
    ]
