# Generated by Django 5.1.1 on 2024-10-29 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0118_alter_animal_cage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="cage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="animals",
                to="dashboard.cage",
            ),
        ),
    ]
