# Generated by Django 4.2.17 on 2025-05-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0118_iacucnote"),
    ]

    operations = [
        migrations.AddField(
            model_name="iacucsubmission",
            name="revision_stages",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
