# Generated by Django 4.2.17 on 2025-01-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0119_organization_primary_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="mentions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
