# Generated by Django 4.2.17 on 2025-05-09 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0119_iacucsubmission_revision_stages"),
    ]

    operations = [
        migrations.AddField(
            model_name="iacucsubmission",
            name="pre_review_member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pre_review_as_member",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="iacucsubmission",
            name="pre_review_veterinarian",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pre_review_as_vet",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
