# Generated by Django 5.1.1 on 2024-10-30 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0119_alter_animal_cage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="cage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="animals",
                to="dashboard.cage",
            ),
        ),
    ]
