# Generated by Django 4.2.17 on 2025-01-22 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0120_message_mentions"),
    ]

    operations = [
        migrations.RemoveField(model_name="message", name="mentions",),
        migrations.AddField(
            model_name="message",
            name="mentions",
            field=models.ManyToManyField(
                blank=True,
                related_name="mentioned_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
