# Generated by Django 4.2.17 on 2025-05-09 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0120_iacucsubmission_pre_review_member_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iacucsubmission",
            name="pre_review_member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_as_member",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="iacucsubmission",
            name="pre_review_veterinarian",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_as_vet",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
