# Generated by Django 4.2.17 on 2025-05-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0121_alter_iacucsubmission_pre_review_member_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="iacucsubmission",
            name="pre_review_member_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="iacucsubmission",
            name="pre_review_vet_approved",
            field=models.BooleanField(default=False),
        ),
    ]
