# Generated by Django 4.2.17 on 2025-01-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0122_user_blocked_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('principal_admin', 'Principal Admin'), ('org_it_admin', 'Organization IT Admin'), ('admin', 'Admin'), ('officer', 'Officer'), ('researcher', 'Researcher'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
    ]
