# Generated by Django 5.1.1 on 2024-10-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0122_alter_observation_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation", name="score", field=models.PositiveIntegerField(),
        ),
    ]
