# Generated by Django 4.2.17 on 2025-01-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0123_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('principal_admin', 'Principal Admin'), ('org_it_admin', 'Organization IT Admin'), ('admin', 'Admin'), ('officer', 'Officer'), ('researcher', 'Researcher'), ('viewer', 'Viewer'), ('approval_member', 'Approval Member')], default='viewer', max_length=20),
        ),
    ]
