# Generated by Django 5.1.1 on 2024-10-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0125_alter_rfidassignment_experiment"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfidassignment",
            name="alert_sent_tumor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rfidassignment",
            name="alert_sent_weight",
            field=models.BooleanField(default=False),
        ),
    ]
