# Generated by Django 4.2.17 on 2025-01-29 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0125_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='age_range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='number_of_animals',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.organization'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='personnel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='species_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='species_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='steps_completed',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='protocol',
            name='weight_range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
