# Generated by Django 5.1.1 on 2024-11-01 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0126_rfidassignment_alert_sent_tumor_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="rfidassignment", name="alert_sent_tumor",),
        migrations.RemoveField(model_name="rfidassignment", name="alert_sent_weight",),
    ]
