# Generated by Django 4.2.17 on 2025-01-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0126_protocol_age_range_protocol_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='certification_body',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='certification_documents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='certification_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='compliance_guidelines',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='ethical_considerations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='ethical_restrictions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='expected_outcomes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='funding_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='funding_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='funding_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='grant_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='methodology_overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='protocol_purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='required_certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='research_areas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='safety_measures',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='special_approvals',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=50),
        ),
        migrations.AddField(
            model_name='protocol',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
