# Generated by Django 4.2.17 on 2025-05-10 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0127_iacucsectionnote"),
    ]

    operations = [
        migrations.CreateModel(
            name="IACUCPersonnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_role", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("organization", models.CharField(max_length=255)),
                ("department", models.CharField(max_length=255)),
                ("home_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=20, null=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personnel_entries",
                        to="dashboard.iacucsubmission",
                    ),
                ),
            ],
        ),
    ]
