# Generated by Django 4.2.17 on 2025-01-29 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0128_user_department_user_mail_code_user_net_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='additional_submitters',
            field=models.ManyToManyField(blank=True, related_name='protocols_as_submitter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='protocol',
            name='administrative_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocols_as_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='protocol',
            name='co_principal_investigator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocols_as_co_pi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='protocol',
            name='principal_investigator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocols_as_pi', to=settings.AUTH_USER_MODEL),
        ),
    ]
