# Generated by Django 5.1.1 on 2024-11-05 16:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0129_experiment_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="specific_dates",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.DateField(), blank=True, default=list, size=None
            ),
        ),
    ]
