# Generated by Django 4.2.17 on 2025-01-29 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0129_protocol_additional_submitters_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProtocolSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex_preference', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Either', 'Either')], max_length=10)),
                ('weight_min', models.FloatField()),
                ('weight_max', models.FloatField()),
                ('weight_unit', models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('lb', 'Pounds')], max_length=10)),
                ('age_min', models.IntegerField()),
                ('age_max', models.IntegerField()),
                ('age_unit', models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], max_length=10)),
                ('strain', models.CharField(blank=True, max_length=255, null=True)),
                ('housing_location', models.CharField(blank=True, max_length=255, null=True)),
                ('room_number', models.CharField(blank=True, max_length=50, null=True)),
                ('number_needed', models.IntegerField()),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_species', to='dashboard.protocol')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.species')),
            ],
        ),
    ]
