# Generated by Django 5.1.1 on 2024-11-06 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0130_calendarevent_specific_dates"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="weightmeasurement",
            unique_together={("animal", "weight", "timestamp")},
        ),
    ]
