# Generated by Django 4.2.17 on 2025-05-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0130_iacucpersonnel_degrees_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="iacucpersonnel",
            name="activity_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="iacucpersonnel",
            name="will_handle_animals",
            field=models.BooleanField(default=False),
        ),
    ]
