# Generated by Django 4.2.17 on 2025-01-29 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0130_species_protocolspecies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProtocolSpecies',
        ),
        migrations.DeleteModel(
            name='Species',
        ),
    ]
