# Generated by Django 4.2.17 on 2025-05-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0131_iacucpersonnel_activity_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="iacucprotocolspecies",
            name="age_range",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="iacucprotocolspecies",
            name="avg_weeks_housed",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="iacucprotocolspecies",
            name="identification_methods",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="iacucprotocolspecies",
            name="is_pathogen_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="iacucprotocolspecies",
            name="max_cages",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="iacucprotocolspecies",
            name="target_weight",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
