# Generated by Django 4.2.17 on 2025-01-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0132_protocol_biological_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='mini_steps_completed',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
