# Generated by Django 4.2.17 on 2025-05-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0132_iacucprotocolspecies_age_range_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="iacucprotocolspecies",
            name="other_justification",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="iacucprotocolspecies",
            name="species_justification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new_model", "New Model"),
                    ("database_exists", "Large Database exists"),
                    (
                        "unique_traits",
                        "Anatomy, Genetics, Physiology, Behavior is Uniquely Suited to the Study",
                    ),
                    (
                        "lowest_phylo",
                        "This is the phylogenetically lowest species that provides adequate size/tissue",
                    ),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
