# Generated by Django 4.2.17 on 2025-01-30 20:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0133_protocol_mini_steps_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='emergency_contacts',
            field=models.ManyToManyField(blank=True, related_name='protocol_emergency_contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
