# Generated by Django 4.2.17 on 2025-01-30 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0134_protocol_emergency_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=255)),
                ('route', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=255)),
                ('secondary_method', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_entries', to='dashboard.protocol')),
            ],
        ),
    ]
