# Generated by Django 4.2.17 on 2025-01-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0135_speciesentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
