# Generated by Django 4.2.17 on 2025-05-11 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0135_alter_speciesuselocation_location_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="speciesuselocation", unique_together=set(),
        ),
    ]
