# Generated by Django 4.2.17 on 2025-01-30 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0136_attachment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dashboard.protocol'),
        ),
    ]
