# Generated by Django 4.2.17 on 2025-05-11 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0136_alter_speciesuselocation_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeciesStrain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strain", models.CharField(max_length=255)),
                ("age", models.CharField(max_length=50)),
                ("weight", models.CharField(max_length=50)),
                ("phenotype", models.TextField(blank=True)),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.iacucprotocolspecies",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.iacucsubmission",
                    ),
                ),
            ],
        ),
    ]
