# Generated by Django 4.2.17 on 2025-01-30 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0137_attachment_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dashboard.animal'),
        ),
    ]
