# Generated by Django 4.2.17 on 2025-01-31 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0138_alter_attachment_animal"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol",
            name="is_draft",
            field=models.BooleanField(default=True),
        ),
    ]
