# Generated by Django 4.2.17 on 2025-05-12 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0139_alter_iacucsubmission_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="iacucsubmission",
            name="dmr_approvals",
            field=models.ManyToManyField(
                blank=True, related_name="dmr_approvals", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="iacucsubmission",
            name="dmr_rejected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="iacucsubmission",
            name="review_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dmr", "Designated Member Review"),
                    ("fcr", "Full Committee Review"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
