# Generated by Django 4.2.17 on 2025-02-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0139_protocol_is_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol",
            name="rationale",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
