# Generated by Django 4.2.17 on 2025-02-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0140_protocol_rationale"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol",
            name="procedures",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
