# Generated by Django 4.2.17 on 2025-02-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0141_protocol_procedures"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol",
            name="alternative_search",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
