# Generated by Django 4.2.17 on 2025-05-12 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0142_alter_iacucsubmission_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("abstain", "Abstain"),
                        ],
                        max_length=10,
                    ),
                ),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.meetingitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("user", "item")},},
        ),
        migrations.AddField(
            model_name="meetingitem",
            name="votes",
            field=models.ManyToManyField(
                related_name="meeting_votes",
                through="dashboard.MeetingVote",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
