# Generated by Django 4.2.17 on 2025-02-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0142_protocol_alternative_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol",
            name="procedure_relationships",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
