# Generated by Django 4.2.17 on 2025-05-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0143_meetingvote_meetingitem_votes"),
    ]

    operations = [
        migrations.AddField(
            model_name="iacucsubmission",
            name="annual_review_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="iacucsubmission",
            name="triennial_review_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
