# Generated by Django 4.2.17 on 2025-02-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0143_protocol_procedure_relationships"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol",
            name="husbandry",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
