# Generated by Django 4.2.17 on 2025-02-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0144_protocol_husbandry"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol",
            name="euthanasia",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
