# Generated by Django 4.2.17 on 2025-05-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0146_iacucpersonnel_renewal_personnel"),
    ]

    operations = [
        migrations.AddField(
            model_name="iacucpersonnel",
            name="adverse_events",
            field=models.TextField(blank=True, null=True),
        ),
    ]
