# Generated by Django 4.2.17 on 2025-02-01 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0148_alter_protocol_status_approvalcomment"),
    ]

    operations = [
        migrations.RemoveField(model_name="approvalcomment", name="status",),
        migrations.AlterField(
            model_name="approvalcomment",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="approvalcomment",
            name="section",
            field=models.CharField(
                choices=[
                    ("rationale", "Rationale"),
                    ("procedures", "Procedures"),
                    ("alternative_search", "Alternative Search"),
                    ("procedure_relationships", "Procedure Relationships"),
                    ("husbandry", "Husbandry"),
                    ("euthanasia", "Euthanasia"),
                    ("additional_notes", "Additional Notes"),
                    ("general", "General"),
                ],
                max_length=50,
            ),
        ),
    ]
