# Generated by Django 4.2.17 on 2025-05-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0150_iacucsubmission_alt_to_procedures"),
    ]

    operations = [
        migrations.AddField(
            model_name="iacucsubmission",
            name="duplication_prevention",
            field=models.TextField(blank=True, null=True),
        ),
    ]
