# Generated by Django 4.2.17 on 2025-02-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0150_alter_approvalcomment_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalcomment",
            name="section",
            field=models.CharField(
                choices=[
                    ("rationale", "Rationale"),
                    ("procedures", "Procedures"),
                    ("alternative_search", "Alternative Search"),
                    ("procedure_relationships", "Procedure Relationships"),
                    ("husbandry", "Husbandry"),
                    ("euthanasia", "Euthanasia"),
                    ("funding", "Funding"),
                    ("guidelines", "Guidelines"),
                    ("additional_notes", "Additional Notes"),
                    ("general", "General"),
                ],
                max_length=50,
            ),
        ),
    ]
