# Generated by Django 4.2.17 on 2025-05-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0151_iacucsubmission_duplication_prevention"),
    ]

    operations = [
        migrations.AddField(
            model_name="iacucsubmission",
            name="future_use_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="iacucsubmission",
            name="future_use_plan",
            field=models.CharField(
                blank=True,
                choices=[
                    ("planned", "Future Changes Planned"),
                    ("no_changes", "No Changes Planned"),
                    ("other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
