# Generated by Django 4.2.17 on 2025-02-02 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0153_protocoltemplate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="protocoltemplate",
            old_name="fields",
            new_name="attributes_selected",
        ),
        migrations.RemoveField(model_name="protocoltemplate", name="description",),
        migrations.RemoveField(model_name="protocoltemplate", name="name",),
        migrations.RemoveField(model_name="protocoltemplate", name="updated_at",),
        migrations.AddField(
            model_name="protocoltemplate",
            name="roles_required",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="protocoltemplate",
            name="template_name",
            field=models.CharField(default="Default Template", max_length=255),
        ),
        migrations.AlterField(
            model_name="protocoltemplate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_protocol_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
