# Generated by Django 4.2.17 on 2025-02-02 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0154_rename_fields_protocoltemplate_attributes_selected_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="animal", name="name",),
        migrations.RemoveField(model_name="animal", name="species_name",),
    ]
