# Generated by Django 4.2.17 on 2025-05-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0155_irbcommittee_irbmember"),
    ]

    operations = [
        migrations.AddField(
            model_name="irbsubmission",
            name="review_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("exempt", "Exempt"),
                    ("expedited", "Expedited"),
                    ("full", "Full Review Required"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="irbsubmission",
            name="revision_stages",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
