# Generated by Django 4.2.17 on 2025-02-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0155_remove_animal_name_remove_animal_species_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="housing_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="rack_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="room_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
