# Generated by Django 4.2.17 on 2025-02-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0156_animal_housing_location_animal_rack_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="buildings",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="organization",
            name="racks",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="organization",
            name="rooms",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
