# Generated by Django 4.2.17 on 2025-05-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0157_alter_irbsubmission_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="type",
            field=models.CharField(
                choices=[("iacuc", "IACUC"), ("irb", "IRB")],
                default="iacuc",
                max_length=10,
            ),
        ),
    ]
