# Generated by Django 4.2.17 on 2025-02-03 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0158_building_remove_organization_buildings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cage",
            name="rack",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cages",
                to="dashboard.rack",
            ),
        ),
    ]
