# Generated by Django 4.2.17 on 2025-05-14 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0158_meeting_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="meetingitem", name="submission",),
        migrations.AddField(
            model_name="meetingitem",
            name="submission_iacuc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.iacucsubmission",
            ),
        ),
        migrations.AddField(
            model_name="meetingitem",
            name="submission_irb",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.irbsubmission",
            ),
        ),
    ]
