# Generated by Django 4.2.17 on 2025-05-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0159_remove_meetingitem_submission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="irbsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Pre Submission", "Pre Submission"),
                    ("Pre Review", "Pre Review"),
                    ("Expedited and Exempt", "Expedited and Exempt"),
                    ("IRB Pre Review", "IRB Pre Review"),
                    ("IRB Review", "IRB Review"),
                    ("IRB Review Revision", "IRB Review Revision"),
                    ("Post IRB Review", "Post IRB Review"),
                    ("Post IRB Review Revision", "Post IRB Review Revision"),
                    ("Approved", "Approved"),
                ],
                default="Draft",
                max_length=30,
            ),
        ),
    ]
