# Generated by Django 4.2.17 on 2025-02-03 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0161_usercertification"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingfolder",
            name="assigned_users",
            field=models.ManyToManyField(
                blank=True, related_name="training_folders", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
