# Generated by Django 4.2.17 on 2025-05-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0162_disclosure"),
    ]

    operations = [
        migrations.AddField(
            model_name="disclosure",
            name="protocol_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="disclosure",
            name="submitted_annual_financials",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
