# Generated by Django 4.2.17 on 2025-02-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0162_trainingfolder_assigned_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingfolder",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
