# Generated by Django 4.2.17 on 2025-05-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0163_disclosure_protocol_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="disclosure",
            name="is_phs_supported",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
