# Generated by Django 4.2.17 on 2025-02-03 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0163_alter_trainingfolder_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usercertification", unique_together=set(),
        ),
        migrations.AddField(
            model_name="certification",
            name="assigned_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_certifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="certification",
            name="course_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="usercertification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_certifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(model_name="usercertification", name="assigned_by",),
    ]
