# Generated by Django 4.2.17 on 2025-05-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0165_disclosure_has_public_entity_interest"),
    ]

    operations = [
        migrations.AddField(
            model_name="disclosure",
            name="has_nonpublic_entity_interest",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
