# Generated by Django 4.2.17 on 2025-02-03 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0165_usercertification_assigned_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocoltemplate",
            name="custom_fields",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="protocoltemplate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
