# Generated by Django 4.2.17 on 2025-05-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0166_disclosure_has_nonpublic_entity_interest"),
    ]

    operations = [
        migrations.AddField(
            model_name="disclosure",
            name="has_intellectual_property",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
