# Generated by Django 4.2.17 on 2025-02-03 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0166_protocoltemplate_custom_fields_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProtocolDesign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fields", models.JSONField(default=list)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.organization",
                    ),
                ),
            ],
        ),
    ]
