# Generated by Django 4.2.17 on 2025-02-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0167_protocoldesign"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol",
            name="uses_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
