# Generated by Django 4.2.17 on 2025-02-04 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0168_protocol_uses_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProtocolInfoStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the mini-step", max_length=255
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in which steps appear"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocol_info_steps",
                        to="dashboard.organization",
                    ),
                ),
            ],
            options={"ordering": ["position"],},
        ),
        migrations.CreateModel(
            name="ProtocolInfoResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "responses",
                    models.JSONField(
                        help_text="Stores user responses as a JSON object"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocol_info_responses",
                        to="dashboard.protocol",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="dashboard.protocolinfostep",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProtocolInfoField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Question or label for the field", max_length=255
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Short Text"),
                            ("textarea", "Long Text"),
                            ("dropdown", "Dropdown"),
                            ("yesno", "Yes/No Question"),
                            ("table", "Table"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        help_text="Used for dropdowns or table column names",
                        null=True,
                    ),
                ),
                (
                    "yes_condition_fields",
                    models.JSONField(
                        blank=True,
                        help_text="Fields to show if Yes is selected",
                        null=True,
                    ),
                ),
                (
                    "no_condition_fields",
                    models.JSONField(
                        blank=True,
                        help_text="Fields to show if No is selected",
                        null=True,
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="dashboard.protocolinfostep",
                    ),
                ),
            ],
            options={"ordering": ["position"],},
        ),
    ]
