# Generated by Django 4.2.17 on 2025-02-04 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0169_protocolinfostep_protocolinforesponse_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MiniStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=1)),
                ("is_required", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MiniStepField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("textarea", "Textarea"),
                            ("number", "Number"),
                            ("dropdown", "Dropdown"),
                            ("file", "File Upload"),
                        ],
                        max_length=20,
                    ),
                ),
                ("options", models.TextField(blank=True, null=True)),
                (
                    "mini_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="dashboard.ministep",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="protocolinforesponse", name="protocol",),
        migrations.RemoveField(model_name="protocolinforesponse", name="step",),
        migrations.RemoveField(model_name="protocolinforesponse", name="submitted_by",),
        migrations.RemoveField(model_name="protocolinfostep", name="organization",),
        migrations.DeleteModel(name="ProtocolInfoField",),
        migrations.DeleteModel(name="ProtocolInfoResponse",),
        migrations.DeleteModel(name="ProtocolInfoStep",),
    ]
