# Generated by Django 4.2.17 on 2025-05-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0169_disclosure_has_sponsored_travel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="position_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("app_viewer", "Application Viewer"),
                    ("app_editor", "Application Editor"),
                    ("dept_app_editor", "Department Application Editor"),
                    ("proposal_reviewer", "Proposal Reviewer"),
                    ("irb_admin", "IRB Admin"),
                    ("iacuc_admin", "IACUC Admin"),
                    ("dept_app_viewer", "Department Application Viewer"),
                    ("agency_user", "Agency Representative"),
                    ("nih_chair", "NIH Chairperson"),
                    ("nih_board_member", "NIH Board Member"),
                    ("nih_sro", "NIH Scientific Review Officer"),
                    ("fund_manager", "Fund Manager"),
                ],
                help_text="Defines the specific application-level position",
                max_length=50,
                null=True,
            ),
        ),
    ]
