# Generated by Django 4.2.17 on 2025-05-21 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0170_alter_user_position_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDictionaryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(max_length=255)),
                ("definition", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Funding", "Funding"),
                            ("Organization", "Organization"),
                            ("Institution", "Institution"),
                            ("Location", "Location"),
                            ("Procedure", "Procedure"),
                            ("Drug", "Drug"),
                            ("Agent", "Agent"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dictionary_entries",
                        to="dashboard.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "term"],
                "unique_together": {("organization", "term", "category")},
            },
        ),
    ]
