# Generated by Django 4.2.17 on 2025-02-04 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0171_protocolministepdata"),
    ]

    operations = [
        migrations.RemoveField(model_name="ministepfield", name="options",),
        migrations.AddField(
            model_name="ministepfield",
            name="required",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="ministepfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("textarea", "Textarea"),
                    ("number", "Number"),
                    ("dropdown", "Dropdown"),
                    ("file", "File Upload"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="ministepfield",
            name="mini_step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.ministep"
            ),
        ),
    ]
