# Generated by Django 4.2.17 on 2025-02-04 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0172_remove_ministepfield_options_ministepfield_required_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="ministepfield", name="required",),
        migrations.AddField(
            model_name="ministepfield",
            name="options",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ministepfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("textarea", "Textarea"),
                    ("number", "Number"),
                    ("dropdown", "Dropdown"),
                    ("file", "File Upload"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ministepfield",
            name="mini_step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="dashboard.ministep",
            ),
        ),
    ]
