# Generated by Django 4.2.17 on 2025-05-21 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0172_alter_userdictionaryentry_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department_name", models.CharField(max_length=255)),
                (
                    "dictionary_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="dashboard.userdictionaryentry",
                    ),
                ),
            ],
        ),
    ]
