# Generated by Django 4.2.17 on 2025-02-04 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0173_remove_ministepfield_required_ministepfield_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ministepfield",
            name="is_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ministepfield",
            name="parent_field",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dependent_fields",
                to="dashboard.ministepfield",
            ),
        ),
        migrations.AddField(
            model_name="ministepfield",
            name="trigger_option",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
