# Generated by Django 4.2.17 on 2025-02-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0174_ministepfield_is_required_ministepfield_parent_field_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol",
            name="answers",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
