# Generated by Django 4.2.17 on 2025-05-21 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0175_userdictionaryentry_agent_category_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="speciesprocedure", unique_together=set(),),
        migrations.AddField(
            model_name="speciesprocedure",
            name="procedure_entry",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category": "procedure"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.userdictionaryentry",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="speciesprocedure",
            unique_together={("submission", "species", "procedure_entry")},
        ),
        migrations.RemoveField(model_name="speciesprocedure", name="procedure_name",),
    ]
