# Generated by Django 4.2.17 on 2025-02-05 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0175_protocol_answers"),
    ]

    operations = [
        migrations.AddField(
            model_name="ministepfield",
            name="allow_dynamic_rows",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ministepfield",
            name="column_names",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ministepfield",
            name="fixed_rows",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ministepfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("textarea", "Textarea"),
                    ("number", "Number"),
                    ("dropdown", "Dropdown"),
                    ("file", "File Upload"),
                    ("table", "Table"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ministepfield",
            name="parent_field",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.ministepfield",
            ),
        ),
    ]
