# Generated by Django 4.2.17 on 2025-02-05 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0176_ministepfield_allow_dynamic_rows_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubMiniStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField()),
                ("trigger_value", models.CharField(blank=True, max_length=255)),
                (
                    "mini_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_mini_steps",
                        to="dashboard.ministep",
                    ),
                ),
                (
                    "trigger_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.ministepfield",
                    ),
                ),
            ],
        ),
    ]
