# Generated by Django 4.2.17 on 2025-05-22 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0176_alter_speciesprocedure_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iacucinternalfundingsource",
            name="department",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category": "department"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="internal_funding_departments",
                to="dashboard.userdictionaryentry",
            ),
        ),
        migrations.AlterField(
            model_name="iacucinternalfundingsource",
            name="fund_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="iacucinternalfundingsource",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category": "organization"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="internal_funding_organizations",
                to="dashboard.userdictionaryentry",
            ),
        ),
    ]
