# Generated by Django 4.2.17 on 2025-02-05 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0177_subministep"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subministep", old_name="mini_step", new_name="parent_mini_step",
        ),
        migrations.AlterField(
            model_name="subministep",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="subministep",
            name="trigger_field",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="triggered_sub_steps",
                to="dashboard.ministepfield",
            ),
        ),
        migrations.AlterField(
            model_name="subministep",
            name="trigger_value",
            field=models.CharField(
                help_text="Dropdown option that triggers this sub-step", max_length=255
            ),
        ),
    ]
