# Generated by Django 4.2.17 on 2025-02-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0178_rename_mini_step_subministep_parent_mini_step_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subministep",
            name="is_required",
            field=models.BooleanField(default=False),
        ),
    ]
