# Generated by Django 4.2.17 on 2025-05-22 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0178_alter_iacucinternalfundingsource_department"),
    ]

    operations = [
        migrations.RemoveField(model_name="speciesvetdrug", name="generic_name",),
        migrations.AddField(
            model_name="speciesvetdrug",
            name="drug_entry",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category": "drug"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="used_in_vetdrugs",
                to="dashboard.userdictionaryentry",
            ),
        ),
        migrations.AlterField(
            model_name="speciesvetdrug",
            name="drug_type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="speciesvetdrug",
            name="is_pharma_grade",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="speciesvetdrug",
            name="non_pharma_justification",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="speciesvetdrug",
            name="procedure_use",
            field=models.CharField(max_length=255),
        ),
    ]
