# Generated by Django 4.2.17 on 2025-05-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0179_remove_speciesvetdrug_generic_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="speciesvetdrug", name="drug_entry",),
        migrations.AddField(
            model_name="speciesvetdrug",
            name="generic_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="speciesvetdrug",
            name="drug_type",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="speciesvetdrug",
            name="is_pharma_grade",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="speciesvetdrug", name="procedure_use", field=models.TextField(),
        ),
    ]
