# Generated by Django 4.2.17 on 2025-02-05 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0179_subministep_is_required"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubMiniStepField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("textarea", "Textarea"),
                            ("number", "Number"),
                            ("dropdown", "Dropdown"),
                            ("file", "File Upload"),
                            ("table", "Table"),
                        ],
                        max_length=50,
                    ),
                ),
                ("options", models.TextField(blank=True, null=True)),
                ("column_names", models.TextField(blank=True, null=True)),
                ("fixed_rows", models.PositiveIntegerField(blank=True, null=True)),
                ("allow_dynamic_rows", models.BooleanField(default=False)),
                ("is_required", models.BooleanField(default=False)),
                (
                    "trigger_option",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "parent_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependent_fields",
                        to="dashboard.subministepfield",
                    ),
                ),
                (
                    "sub_mini_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="dashboard.subministep",
                    ),
                ),
            ],
        ),
    ]
