# Generated by Django 4.2.17 on 2025-02-05 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0180_subministepfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="subministep",
            name="fields",
            field=models.ManyToManyField(
                related_name="sub_step_fields", to="dashboard.ministepfield"
            ),
        ),
        migrations.AlterField(
            model_name="subministep",
            name="parent_mini_step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.ministep"
            ),
        ),
        migrations.AlterField(
            model_name="subministep",
            name="trigger_field",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.ministepfield",
            ),
        ),
        migrations.AlterField(
            model_name="subministep",
            name="trigger_value",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="subministepfield",
            name="sub_mini_step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_mini_step_fields",
                to="dashboard.subministep",
            ),
        ),
    ]
