# Generated by Django 4.2.17 on 2025-05-23 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0181_amendmentchangelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="iacucsubmission",
            name="original_submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="amendments",
                to="dashboard.iacucsubmission",
            ),
        ),
    ]
