# Generated by Django 4.2.17 on 2025-02-05 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0181_subministep_fields_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="subministep", name="fields",),
        migrations.AlterField(
            model_name="subministep",
            name="parent_mini_step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_mini_steps",
                to="dashboard.ministep",
            ),
        ),
        migrations.AlterField(
            model_name="subministep",
            name="trigger_field",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="triggered_sub_steps",
                to="dashboard.ministepfield",
            ),
        ),
        migrations.AlterField(
            model_name="subministep",
            name="trigger_value",
            field=models.CharField(
                help_text="Dropdown option that triggers this sub-step", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="subministepfield",
            name="sub_mini_step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="dashboard.subministep",
            ),
        ),
    ]
