# Generated by Django 4.2.17 on 2025-02-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0182_remove_subministep_fields_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol",
            name="triggered_sub_steps",
            field=models.JSONField(default=list),
        ),
    ]
