# Generated by Django 4.2.17 on 2025-02-25 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0183_protocol_triggered_sub_steps"),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=255)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("checkbox", "Checkbox"),
                            ("radio", "Radio"),
                        ],
                        max_length=20,
                    ),
                ),
                ("options", models.TextField(blank=True, null=True)),
                ("required", models.BooleanField(default=False)),
                (
                    "pdf_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="dashboard.pdftemplate",
                    ),
                ),
            ],
        ),
    ]
