# Generated by Django 4.2.17 on 2025-05-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0184_alter_iacucsubmission_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="iacucsubmission",
            name="is_superseded",
            field=models.BooleanField(default=False),
        ),
    ]
