# Generated by Django 4.2.17 on 2025-02-25 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0185_uploadedpdf"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pdftemplate", old_name="created_at", new_name="uploaded_at",
        ),
        migrations.RemoveField(model_name="pdftemplate", name="created_by",),
        migrations.RemoveField(model_name="pdftemplate", name="description",),
        migrations.RemoveField(model_name="pdftemplate", name="editable_fields",),
        migrations.AddField(
            model_name="pdftemplate",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
