# Generated by Django 4.2.17 on 2025-02-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0186_rename_created_at_pdftemplate_uploaded_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SF424Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("date", "Date"),
                            ("number", "Number"),
                        ],
                        max_length=50,
                    ),
                ),
                ("options", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
