# Generated by Django 4.2.17 on 2025-05-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0187_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agency_badge',
            field=models.ImageField(blank=True, null=True, upload_to='agency_badges/'),
        ),
    ]
