# Generated by Django 4.2.17 on 2025-07-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0194_alter_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_2fa_verified',
            field=models.BooleanField(default=False),
        ),
    ]
