# Generated by Django 4.2.17 on 2025-08-05 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0199_remove_conversation_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.organization'),
        ),
        migrations.AddField(
            model_name='irbsubmission',
            name='analyst_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='irbsubmission',
            name='certification_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='irbsubmission',
            name='final_approval_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='irbsubmission',
            name='irb_board_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='irbsubmission',
            name='irb_office_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
