# Generated by Django 4.2.17 on 2025-09-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0200_conversation_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('principal_admin', 'Principal Admin'), ('org_it_admin', 'Organization IT Admin'), ('admin', 'Admin'), ('officer', 'Officer'), ('researcher', 'Researcher'), ('viewer', 'Viewer'), ('approval_member', 'Approval Member'), ('product_support', 'Product Support'), ('sales_rep', 'Sales Representative'), ('customer_success', 'Customer Success'), ('implementation_rep', 'Implementation Representative'), ('fund_manager', 'Fund Manager')], default='viewer', max_length=20),
        ),
    ]
