# Generated by Django 4.2.17 on 2025-11-04 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0202_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedpackage',
            name='deviation_authorization_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='packageform',
            name='form_type',
            field=models.CharField(choices=[('sf424', 'SF-424'), ('rr_budget', 'RR Budget'), ('phs_plan', 'PHS Plan'), ('skp', 'Senior Key Person'), ('site', 'Project Site'), ('rr_other_info', 'RR Other Info'), ('phs_cover', 'PHS Cover'), ('phs_subjects', 'PHS Human Subjects'), ('deviation_auth', 'Deviation Authorization')], default='unknown', max_length=100),
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('total_size', models.BigIntegerField()),
                ('part_size', models.IntegerField()),
                ('total_parts', models.IntegerField()),
                ('received_parts', models.IntegerField(default=0)),
                ('storage_backend', models.CharField(default='local', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.conversation')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='attachments/thumbs/')),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dashboard.conversation')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
