# Generated by Django 4.2.17 on 2025-10-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0202_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='remember_me',
            field=models.BooleanField(default=False, help_text='Skip email and 2FA verification when enabled'),
        ),
    ]
