# Generated by Django 4.2.17 on 2025-11-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0203_submittedpackage_deviation_authorization_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedpackage',
            name='cd_511_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packageform',
            name='form_type',
            field=models.CharField(choices=[('sf424', 'SF-424'), ('rr_budget', 'RR Budget'), ('phs_plan', 'PHS Plan'), ('skp', 'Senior Key Person'), ('site', 'Project Site'), ('rr_other_info', 'RR Other Info'), ('phs_cover', 'PHS Cover'), ('phs_subjects', 'PHS Human Subjects'), ('deviation_auth', 'Deviation Authorization'), ('cd_511', 'CD-511 (Certification Regarding Lobbying)')], default='unknown', max_length=100),
        ),
    ]
