# Generated by Django 4.2.17 on 2025-10-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0203_add_remember_me_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='remember_me_last_verified',
            field=models.DateTimeField(blank=True, help_text='Last time user was verified with remember_me enabled', null=True),
        ),
    ]
