# Generated by Django 4.2.17 on 2025-11-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0204_submittedpackage_cd_511_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedpackage',
            name='neh_institutional_profile_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
