# Generated by Django 4.2.17 on 2025-12-07 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0204_add_remember_me_expiry'),
        ('dashboard', '0205_submittedpackage_neh_institutional_profile_data'),
    ]

    operations = [
    ]
