# Generated by Django 4.2.17 on 2025-12-15 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0206_merge_20251123_1828'),
        ('dashboard', '0206_merge_20251206_2049'),
    ]

    operations = [
    ]
